package com.github.azeroth.game.entity.item.enums;

public enum ItemModifier {
    TRANSMOG_APPEARANCE_ALL_SPECS,
    TRANSMOG_APPEARANCE_SPEC_1,
    UPGRADE_ID,
    BATTLE_PET_SPECIES_ID,
    BATTLE_PET_BREED_DATA, // (breedId) | (breedQuality << 24)
    BATTLE_PET_LEVEL,
    BATTLE_PET_DISPLAY_ID,
    ENCHANT_ILLUSION_ALL_SPECS,
    ARTIFACT_APPEARANCE_ID,
    TIMEWALKER_LEVEL,
    ENCHANT_ILLUSION_SPEC_1,
    TRANSMOG_APPEARANCE_SPEC_2,
    ENCHANT_ILLUSION_SPEC_2,
    TRANSMOG_APPEARANCE_SPEC_3,
    ENCHANT_ILLUSION_SPEC_3,
    TRANSMOG_APPEARANCE_SPEC_4,
    ENCHANT_ILLUSION_SPEC_4,
    CHALLENGE_MAP_CHALLENGE_MODE_ID,
    CHALLENGE_KEYSTONE_LEVEL,
    CHALLENGE_KEYSTONE_AFFIX_ID_1,
    CHALLENGE_KEYSTONE_AFFIX_ID_2,
    CHALLENGE_KEYSTONE_AFFIX_ID_3,
    CHALLENGE_KEYSTONE_AFFIX_ID_4,
    ARTIFACT_KNOWLEDGE_LEVEL,
    ARTIFACT_TIER,
    MAX_ITEM_MODIFIERS
}
