package com.github.azeroth.game.networking.packet.clientconfig;

public enum AccountDataType {
    GLOBAL_CONFIG_CACHE,
    PER_CHARACTER_CONFIG_CACHE,
    GLOBAL_BINDINGS_CACHE,
    PER_CHARACTER_BINDINGS_CACHE,
    GLOBAL_MACROS_CACHE,
    PER_CHARACTER_MACROS_CACHE,
    PER_CHARACTER_LAYOUT_CACHE,
    PER_CHARACTER_CHAT_CACHE,
    GLOBAL_TTS_CACHE,
    PER_CHARACTER_TTS_CACHE,
    GLOBAL_FLAGGED_CACHE,
    PER_CHARACTER_FLAGGED_CACHE,
    PER_CHARACTER_CLICK_BINDINGS_CACHE,
    GLOBAL_EDIT_MODE_CACHE,
    PER_CHARACTER_EDIT_MODE_CACHE,
    GLOBAL_FRONTEND_CHAT_SETTINGS,
    GLOBAL_CHARACTER_LIST_ORDER,
    GLOBAL_COOLDOWN_MANAGER,
    PER_CHARACTER_COOLDOWN_MANAGER2,
    GLOBAL_SHOP2_PENDING_ORDERS
}
