[versions]

slf4j = "2.0.13"
netty = "4.2.7.Final"
springBoot = "3.3.2"
junit = "5.10.2"
lombok = "1.18.34"
protobuf = "4.28.0"
iouring = "0.0.21.Final"
h2database = "2.3.232"
gdx = "1.13.0"
detour = "1.5.11"


[libraries]

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
netty-handler = { group = "io.netty", name = "netty-handler", version.ref = "netty" }
netty-codec-http = { group = "io.netty", name = "netty-codec-http", version.ref = "netty" }
netty-transport-native-epoll = { group = "io.netty", name = "netty-transport-native-epoll", version.ref = "netty" }
netty-transport-native-kqueue = { group = "io.netty", name = "netty-transport-native-kqueue", version.ref = "netty" }
netty-transport-native-iouring = { group = "io.netty.incubator", name = "netty-incubator-transport-native-io_uring", version.ref = "iouring"}
springboot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "springBoot" }
springboot-data-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-jdbc", version.ref = "springBoot" }
springboot-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator", version.ref = "springBoot" }
springboot-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version.ref = "springBoot" }
protobuf = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf" }
protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf"}
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
gdx = { group = "com.badlogicgames.gdx", name = "gdx", version.ref = "gdx" }
recast = { group = "org.recast4j", name = "detour", version.ref = "detour" }


# Testing

test-junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
test-junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
test-junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
springboot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }
h2database = { group = "com.h2database", name = "h2", version.ref = "h2database" }


[bundles]

[plugins]
springboot = { id = "org.springframework.boot", version.ref = "springBoot" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }

