package com.github.azeroth.game.spell.auras.enums;

public enum AuraType {
    NONE,
    BIND_SIGHT,
    MOD_POSSESS,
    PERIODIC_DAMAGE,
    DUMMY,
    MOD_CONFUSE,
    MOD_CHARM,
    MOD_FEAR,
    PERIODIC_HEAL,
    MOD_ATTACKSPEED,
    MOD_THREAT,
    MOD_TAUNT,
    MOD_STUN,
    MOD_DAMAGE_DONE,
    MOD_DAMAGE_TAKEN,
    DAMAGE_SHIELD,
    MOD_STEALTH,
    MOD_STEALTH_DETECT,
    MOD_INVISIBILITY,
    MOD_INVISIBILITY_DETECT,
    OBS_MOD_HEALTH,   // 20, 21 unofficial
    OBS_MOD_POWER,
    MOD_RESISTANCE,
    PERIODIC_TRIGGER_SPELL,
    PERIODIC_ENERGIZE,
    MOD_PACIFY,
    MOD_ROOT,
    MOD_SILENCE,
    REFLECT_SPELLS,
    MOD_STAT,
    MOD_SKILL,
    MOD_INCREASE_SPEED,
    MOD_INCREASE_MOUNTED_SPEED,
    MOD_DECREASE_SPEED,
    MOD_INCREASE_HEALTH,
    MOD_INCREASE_ENERGY,
    MOD_SHAPESHIFT,
    EFFECT_IMMUNITY,
    STATE_IMMUNITY,
    SCHOOL_IMMUNITY,
    DAMAGE_IMMUNITY,
    DISPEL_IMMUNITY,
    PROC_TRIGGER_SPELL,
    PROC_TRIGGER_DAMAGE,
    TRACK_CREATURES,
    TRACK_RESOURCES,
    SPELL_AURA_46,   // Ignore all Gear test spells
    MOD_PARRY_PERCENT,
    PERIODIC_TRIGGER_SPELL_FROM_CLIENT,   // One periodic spell
    MOD_DODGE_PERCENT,
    MOD_CRITICAL_HEALING_AMOUNT,
    MOD_BLOCK_PERCENT,
    MOD_WEAPON_CRIT_PERCENT,
    PERIODIC_LEECH,
    MOD_HIT_CHANCE,
    MOD_SPELL_HIT_CHANCE,
    TRANSFORM,
    MOD_SPELL_CRIT_CHANCE,
    MOD_INCREASE_SWIM_SPEED,
    MOD_DAMAGE_DONE_CREATURE,
    MOD_PACIFY_SILENCE,
    MOD_SCALE,
    PERIODIC_HEALTH_FUNNEL,
    MOD_ADDITIONAL_POWER_COST,
    PERIODIC_MANA_LEECH,
    MOD_CASTING_SPEED_NOT_STACK,
    FEIGN_DEATH,
    MOD_DISARM,
    MOD_STALKED,
    SCHOOL_ABSORB,
    PERIODIC_WEAPON_PERCENT_DAMAGE,
    STORE_TELEPORT_RETURN_POINT,
    MOD_POWER_COST_SCHOOL_PCT,
    MOD_BASE_POWER_COST_SCHOOL,
    REFLECT_SPELLS_SCHOOL,
    MOD_LANGUAGE,
    FAR_SIGHT,
    MECHANIC_IMMUNITY,
    MOUNTED,
    MOD_DAMAGE_PERCENT_DONE,
    MOD_PERCENT_STAT,
    SPLIT_DAMAGE_PCT,
    WATER_BREATHING,
    MOD_BASE_RESISTANCE,
    MOD_REGEN,
    MOD_POWER_REGEN,
    CHANNEL_DEATH_ITEM,
    MOD_DAMAGE_PERCENT_TAKEN,
    MOD_HEALTH_REGEN_PERCENT,
    PERIODIC_DAMAGE_PERCENT,
    SPELL_AURA_90,   // old MOD_RESIST_CHANCE
    MOD_DETECT_RANGE,
    PREVENTS_FLEEING,
    MOD_UNATTACKABLE,
    INTERRUPT_REGEN,
    GHOST,
    SPELL_MAGNET,
    MANA_SHIELD,
    MOD_SKILL_TALENT,
    MOD_ATTACK_POWER,
    AURAS_VISIBLE,
    MOD_RESISTANCE_PCT,
    MOD_MELEE_ATTACK_POWER_VERSUS,
    MOD_TOTAL_THREAT,
    WATER_WALK,
    FEATHER_FALL,
    HOVER,
    ADD_FLAT_MODIFIER,
    ADD_PCT_MODIFIER,
    ADD_TARGET_TRIGGER,
    MOD_POWER_REGEN_PERCENT,
    INTERCEPT_MELEE_RANGED_ATTACKS,
    OVERRIDE_CLASS_SCRIPTS,
    MOD_RANGED_DAMAGE_TAKEN,
    MOD_RANGED_DAMAGE_TAKEN_PCT,
    MOD_HEALING,
    MOD_REGEN_DURING_COMBAT,
    MOD_MECHANIC_RESISTANCE,
    MOD_HEALING_PCT,
    PVP_TALENTS,
    UNTRACKABLE,
    EMPATHY,
    MOD_OFFHAND_DAMAGE_PCT,
    MOD_TARGET_RESISTANCE,
    MOD_RANGED_ATTACK_POWER,
    SPELL_AURA_125,
    MOD_MELEE_DAMAGE_TAKEN_PCT,
    RANGED_ATTACK_POWER_ATTACKER_BONUS,
    MOD_FIXATE,
    MOD_SPEED_ALWAYS,
    MOD_MOUNTED_SPEED_ALWAYS,
    MOD_RANGED_ATTACK_POWER_VERSUS,
    MOD_INCREASE_ENERGY_PERCENT,
    MOD_INCREASE_HEALTH_PERCENT,
    MOD_MANA_REGEN_INTERRUPT,
    MOD_HEALING_DONE,
    MOD_HEALING_DONE_PERCENT,
    MOD_TOTAL_STAT_PERCENTAGE,
    MOD_MELEE_HASTE,
    FORCE_REACTION,
    MOD_RANGED_HASTE,
    SPELL_AURA_141,  // old MOD_RANGED_AMMO_HASTE, unused now
    MOD_BASE_RESISTANCE_PCT,
    MOD_RECOVERY_RATE_BY_SPELL_LABEL,
    SAFE_FALL,
    MOD_INCREASE_HEALTH_PERCENT2,
    ALLOW_TAME_PET_TYPE,
    MECHANIC_IMMUNITY_MASK,
    MOD_CHARGE_RECOVERY_RATE,
    REDUCE_PUSHBACK,  //    Reduce Pushback
    MOD_BLOCKVALUE_PCT,  // NYI
    TRACK_STEALTHED,  //    Track Stealthed
    MOD_DETECTED_RANGE,  //    Mod Detected Range
    MOD_AUTOATTACK_RANGE,
    MOD_STEALTH_LEVEL,  //    Stealth Level Modifier
    MOD_WATER_BREATHING,  //    Mod Water Breathing
    MOD_REPUTATION_GAIN,  //    Mod Reputation Gain
    MOD_PET_DAMAGE_TAKEN_PCT,  // NYI
    ALLOW_TALENT_SWAPPING,
    NO_PVP_CREDIT,
    SPELL_AURA_160,  // old MOD_AOE_AVOIDANCE. Unused 4.3.4
    MOD_HEALTH_REGEN_IN_COMBAT,
    POWER_BURN,
    MOD_CRIT_DAMAGE_BONUS,
    FORCE_BREATH_BAR,
    SPELL_AURA_165,
    MOD_ATTACK_POWER_PCT,
    MOD_RANGED_ATTACK_POWER_PCT,
    MOD_DAMAGE_DONE_VERSUS,
    SET_FFA_PVP,
    DETECT_AMORE,
    MOD_SPEED_NOT_STACK,
    MOD_MOUNTED_SPEED_NOT_STACK,
    MOD_CHARGE_RECOVERY_RATE_BY_TYPE_MASK,
    MOD_SPELL_DAMAGE_OF_STAT_PERCENT,  // by defeult intelect, dependent from MOD_SPELL_HEALING_OF_STAT_PERCENT
    MOD_SPELL_HEALING_OF_STAT_PERCENT,
    SPIRIT_OF_REDEMPTION,
    AOE_CHARM,
    MOD_MAX_POWER_PCT,
    MOD_POWER_DISPLAY,
    MOD_FLAT_SPELL_DAMAGE_VERSUS,
    MOD_SPELL_CURRENCY_REAGENTS_COUNT_PCT,  // NYI
    SUPPRESS_ITEM_PASSIVE_EFFECT_BY_SPELL_LABEL,
    MOD_CRIT_CHANCE_VERSUS_TARGET_HEALTH,
    MOD_ATTACKER_MELEE_HIT_CHANCE,
    MOD_ATTACKER_RANGED_HIT_CHANCE,
    MOD_ATTACKER_SPELL_HIT_CHANCE,
    MOD_ATTACKER_MELEE_CRIT_CHANCE,
    MOD_UI_HEALING_RANGE,
    MOD_RATING,
    MOD_FACTION_REPUTATION_GAIN,
    USE_NORMAL_MOVEMENT_SPEED,
    MOD_MELEE_RANGED_HASTE,
    MELEE_SLOW,
    MOD_TARGET_ABSORB_SCHOOL,
    LEARN_SPELL,
    MOD_COOLDOWN,  // only 24818 Noxious Breath
    MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE,
    MOD_COMBAT_RATING_FROM_COMBAT_RATING,
    SPELL_AURA_199,  // old MOD_INCREASES_SPELL_PCT_TO_HIT. unused 4.3.4
    MOD_XP_PCT,
    FLY,
    IGNORE_COMBAT_RESULT,
    PREVENT_INTERRUPT,
    PREVENT_CORPSE_RELEASE,  // NYI
    MOD_CHARGE_RECOVERY_BY_TYPE_MASK,
    MOD_INCREASE_VEHICLE_FLIGHT_SPEED,
    MOD_INCREASE_MOUNTED_FLIGHT_SPEED,
    MOD_INCREASE_FLIGHT_SPEED,
    MOD_MOUNTED_FLIGHT_SPEED_ALWAYS,
    MOD_VEHICLE_SPEED_ALWAYS,
    MOD_FLIGHT_SPEED_NOT_STACK,
    MOD_SOURCE_HONOR_GAIN_PCT, // MiscvalueA is a bitmask that defines which source of honor is affected
    MOD_RAGE_FROM_DAMAGE_DEALT,
    SPELL_AURA_214,
    ARENA_PREPARATION,
    HASTE_SPELLS,
    MOD_MELEE_HASTE_2,
    ADD_PCT_MODIFIER_BY_SPELL_LABEL,
    ADD_FLAT_MODIFIER_BY_SPELL_LABEL,
    MOD_ABILITY_SCHOOL_MASK,  // NYI
    MOD_DETAUNT,
    REMOVE_TRANSMOG_COST,
    REMOVE_BARBER_SHOP_COST,
    LEARN_TALENT,  // NYI
    MOD_VISIBILITY_RANGE,
    PERIODIC_DUMMY,
    PERIODIC_TRIGGER_SPELL_WITH_VALUE,
    DETECT_STEALTH,
    MOD_AOE_DAMAGE_AVOIDANCE,
    MOD_MAX_HEALTH,
    PROC_TRIGGER_SPELL_WITH_VALUE,
    MECHANIC_DURATION_MOD,
    CHANGE_MODEL_FOR_ALL_HUMANOIDS,  // client-side only
    MECHANIC_DURATION_MOD_NOT_STACK,
    MOD_HOVER_NO_HEIGHT_OFFSET,
    CONTROL_VEHICLE,
    SPELL_AURA_237,
    SPELL_AURA_238,
    SPELL_AURA_239, // old MOD_SCALE_2
    MOD_EXPERTISE,
    FORCE_MOVE_FORWARD,
    MOD_SPELL_DAMAGE_FROM_HEALING,
    MOD_FACTION,
    COMPREHEND_LANGUAGE,
    MOD_AURA_DURATION_BY_DISPEL,
    MOD_AURA_DURATION_BY_DISPEL_NOT_STACK,
    CLONE_CASTER,
    SPELL_AURA_248,
    MOD_DAMAGE_PERCENT_DONE_BY_TARGET_AURA_MECHANIC,
    MOD_INCREASE_HEALTH_2,
    MOD_ENEMY_DODGE,
    MOD_SPEED_SLOW_ALL,
    MOD_BLOCK_CRIT_CHANCE,
    MOD_DISARM_OFFHAND,
    MOD_MECHANIC_DAMAGE_TAKEN_PERCENT,
    NO_REAGENT_USE,
    SPELL_AURA_257,
    OVERRIDE_SUMMONED_OBJECT,
    MOD_HOT_PCT,
    SCREEN_EFFECT,
    PHASE,
    ABILITY_IGNORE_AURASTATE,
    DISABLE_CASTING_EXCEPT_ABILITIES,
    DISABLE_ATTACKING_EXCEPT_ABILITIES,
    SPELL_AURA_265,
    SET_VIGNETTE,
    MOD_IMMUNE_AURA_APPLY_SCHOOL,
    MOD_ARMOR_PCT_FROM_STAT,
    SPELL_AURA_269,
    MOD_SCHOOL_MASK_DAMAGE_FROM_CASTER,
    MOD_SPELL_DAMAGE_FROM_CASTER,
    MOD_BLOCK_VALUE_PCT,  // NYI
    X_RAY,
    MOD_BLOCK_VALUE_FLAT,  // NYI
    MOD_IGNORE_SHAPESHIFT,
    MOD_DAMAGE_DONE_FOR_MECHANIC,
    SPELL_AURA_277,  // old MOD_MAX_AFFECTED_TARGETS. unused 4.3.4
    MOD_DISARM_RANGED,
    INITIALIZE_IMAGES,
    SPELL_AURA_280,  // old MOD_ARMOR_PENETRATION_PCT unused 4.3.4
    PROVIDE_SPELL_FOCUS,
    SPELL_AURA_282,
    MOD_HEALING_RECEIVED,  // Possibly only for some spell family class spells
    LINKED,
    LINKED_2,
    MOD_RECOVERY_RATE,
    DEFLECT_SPELLS,
    IGNORE_HIT_DIRECTION,
    PREVENT_DURABILITY_LOSS,
    MOD_CRIT_PCT,
    MOD_XP_QUEST_PCT,
    OPEN_STABLE,
    OVERRIDE_SPELLS,
    PREVENT_REGENERATE_POWER,
    MOD_PERIODIC_DAMAGE_TAKEN,
    SET_VEHICLE_ID,
    MOD_ROOT_DISABLE_GRAVITY,
    MOD_STUN_DISABLE_GRAVITY,
    SPELL_AURA_299,
    SHARE_DAMAGE_PCT,
    SCHOOL_HEAL_ABSORB,
    SPELL_AURA_302,
    MOD_DAMAGE_DONE_VERSUS_AURASTATE,
    MOD_FAKE_INEBRIATE,
    MOD_MINIMUM_SPEED,
    MOD_CRIT_CHANCE_FOR_CASTER,
    CAST_WHILE_WALKING_BY_SPELL_LABEL,
    MOD_CRIT_CHANCE_FOR_CASTER_WITH_ABILITIES,
    MOD_RESILIENCE,  // NYI
    MOD_CREATURE_AOE_DAMAGE_AVOIDANCE,
    IGNORE_COMBAT,  // NYI
    ANIM_REPLACEMENT_SET,
    MOUNT_ANIM_REPLACEMENT_SET,
    PREVENT_RESURRECTION,
    UNDERWATER_WALKING,
    SCHOOL_ABSORB_OVERKILL,
    MOD_SPELL_POWER_PCT,
    MASTERY,
    MOD_MELEE_HASTE_3,
    SPELL_AURA_320,
    MOD_NO_ACTIONS,
    INTERFERE_TARGETTING,
    SPELL_AURA_323,  // Not used in 4.3.4
    OVERRIDE_UNLOCKED_AZERITE_ESSENCE_RANK,  // testing aura
    LEARN_PVP_TALENT,  // NYI
    PHASE_GROUP,  // Puts the player in all the phases that are in the group with id = miscB
    PHASE_ALWAYS_VISIBLE,  // Sets PhaseShiftFlags::AlwaysVisible
    TRIGGER_SPELL_ON_POWER_PCT,  // Triggers spell when power goes above (MiscB ) or falls below (MiscB ) specified percent value (once, not every time condition has meet)
    MOD_POWER_GAIN_PCT,
    CAST_WHILE_WALKING,
    FORCE_WEATHER,
    OVERRIDE_ACTIONBAR_SPELLS,
    OVERRIDE_ACTIONBAR_SPELLS_TRIGGERED,  // Spells cast with this override have no cast time or power cost
    MOD_AUTOATTACK_CRIT_CHANCE,
    SPELL_AURA_335,
    MOUNT_RESTRICTIONS,
    SPELL_AURA_337,
    MOD_DURABILITY_LOSS,
    MOD_CRIT_CHANCE_FOR_CASTER_PET,
    MOD_RESURRECTED_HEALTH_BY_GUILD_MEMBER,  // Increases health gained when resurrected by a guild member by X
    MOD_SPELL_CATEGORY_COOLDOWN,  // Modifies cooldown of all spells using affected category
    MOD_MELEE_RANGED_HASTE_2,
    MOD_MELEE_DAMAGE_FROM_CASTER,
    MOD_AUTOATTACK_DAMAGE,
    BYPASS_ARMOR_FOR_CASTER,
    ENABLE_ALT_POWER,
    SPELL_AURA_347,
    MOD_MONEY_GAIN,  // Modifies gold gains from source: [Misc , Quests][Misc , Loot]
    MOD_CURRENCY_GAIN,
    SPELL_AURA_350,
    MOD_CURRENCY_CATEGORY_GAIN_PCT,
    SPELL_AURA_352,
    MOD_CAMOUFLAGE,  // NYI
    MOD_HEALING_DONE_PCT_VERSUS_TARGET_HEALTH,  // Restoration Shaman mastery - mod healing based on target's health (less = more healing)
    MOD_CASTING_SPEED,  // NYI
    PROVIDE_TOTEM_CATEGORY,
    ENABLE_BOSS1_UNIT_FRAME,
    WORGEN_ALTERED_FORM,
    MOD_HEALING_DONE_VERSUS_AURASTATE,
    PROC_TRIGGER_SPELL_COPY,  // Procs the same spell that caused this proc (Dragonwrath, Tarecgosa's Rest)
    OVERRIDE_AUTOATTACK_WITH_MELEE_SPELL,
    SPELL_AURA_362,  // Not used in 4.3.4
    MOD_NEXT_SPELL,  // Used by 101601 Throw Totem - causes the client to initialize spell cast with specified spell
    SPELL_AURA_364,  // Not used in 4.3.4
    MAX_FAR_CLIP_PLANE,  // Overrides client's View Distance setting to max("Fair", current_setting) and turns off terrain display
    OVERRIDE_SPELL_POWER_BY_AP_PCT,  // NYI - Sets spellpower equal to % of attack power, discarding all other bonuses (from gear and buffs)
    OVERRIDE_AUTOATTACK_WITH_RANGED_SPELL,  // NYI
    SPELL_AURA_368,  // Not used in 4.3.4
    ENABLE_POWER_BAR_TIMER,
    SPELL_OVERRIDE_NAME_GROUP,  // picks a random SpellOverrideName id from a group (group id in miscValue)
    SPELL_AURA_371,
    OVERRIDE_MOUNT_FROM_SET,  // NYI
    MOD_SPEED_NO_CONTROL,  // NYI
    MODIFY_FALL_DAMAGE_PCT,
    HIDE_MODEL_AND_EQUIPEMENT_SLOTS,
    MOD_CURRENCY_GAIN_FROM_SOURCE,  // NYI
    CAST_WHILE_WALKING_ALL,  // Enables casting all spells while moving
    MOD_POSSESS_PET,
    MOD_MANA_REGEN_PCT,
    SPELL_AURA_380,
    MOD_DAMAGE_TAKEN_FROM_CASTER_PET,  // NYI
    MOD_PET_STAT_PCT,  // NYI
    IGNORE_SPELL_COOLDOWN,
    SPELL_AURA_384,
    SPELL_AURA_385,
    SPELL_AURA_386,
    SPELL_AURA_387,
    MOD_TAXI_FLIGHT_SPEED,  // NYI
    SPELL_AURA_389,
    SPELL_AURA_390,
    SPELL_AURA_391,
    SPELL_AURA_392,
    BLOCK_SPELLS_IN_FRONT,  // NYI
    SHOW_CONFIRMATION_PROMPT,
    AREA_TRIGGER,
    TRIGGER_SPELL_ON_POWER_AMOUNT,  // Triggers spell when power goes above (MiscA ) or falls below (MiscA ) specified percent value (once, not every time condition has meet)
    BATTLEGROUND_PLAYER_POSITION_FACTIONAL,
    BATTLEGROUND_PLAYER_POSITION,
    MOD_TIME_RATE,
    MOD_SKILL_2,
    ACT_AS_CONTROL_ZONE,
    MOD_OVERRIDE_POWER_DISPLAY,
    OVERRIDE_SPELL_VISUAL,
    OVERRIDE_ATTACK_POWER_BY_SP_PCT,
    MOD_RATING_PCT,
    KEYBOUND_OVERRIDE,
    MOD_FEAR_2,  // NYI
    SET_ACTION_BUTTON_SPELL_COUNT,
    CAN_TURN_WHILE_FALLING,
    SPELL_AURA_410,
    MOD_MAX_CHARGES,
    SPELL_AURA_412,
    MOD_RANGED_ATTACK_DEFLECT_CHANCE,  // NYI
    MOD_RANGED_ATTACK_BLOCK_CHANCE_IN_FRONT,  // NYI
    SPELL_AURA_415,
    MOD_COOLDOWN_BY_HASTE_REGEN,
    MOD_GLOBAL_COOLDOWN_BY_HASTE_REGEN,
    MOD_MAX_POWER,
    MOD_BASE_MANA_PCT,
    MOD_BATTLE_PET_XP_PCT,
    MOD_ABSORB_EFFECTS_DONE_PCT,  // NYI
    MOD_ABSORB_EFFECTS_TAKEN_PCT,  // NYI
    MOD_MANA_COST_PCT,
    CASTER_IGNORE_LOS,  // NYI
    SPELL_AURA_425,
    SPELL_AURA_426,
    SCALE_PLAYER_LEVEL,  // NYI
    LINKED_SUMMON,
    MOD_SUMMON_DAMAGE,  // NYI - increases damage done by all summons, not just controlled pets
    PLAY_SCENE,
    MOD_OVERRIDE_ZONE_PVP_TYPE,
    SPELL_AURA_432,
    SPELL_AURA_433,
    SPELL_AURA_434,
    SPELL_AURA_435,
    MOD_ENVIRONMENTAL_DAMAGE_TAKEN,
    MOD_MINIMUM_SPEED_RATE,
    PRELOAD_PHASE,  // NYI
    SPELL_AURA_439,
    MOD_MULTISTRIKE_DAMAGE,  // NYI
    MOD_MULTISTRIKE_CHANCE,  // NYI
    MOD_READINESS,  // NYI
    MOD_LEECH,  // NYI
    SPELL_AURA_444,
    SPELL_AURA_445,
    SPELL_AURA_446,
    MOD_XP_FROM_CREATURE_TYPE,
    SPELL_AURA_448,
    SPELL_AURA_449,
    SPELL_AURA_450,
    OVERRIDE_PET_SPECS,
    SPELL_AURA_452,
    CHARGE_RECOVERY_MOD,
    CHARGE_RECOVERY_MULTIPLIER,
    MOD_ROOT_2,
    CHARGE_RECOVERY_AFFECTED_BY_HASTE,
    CHARGE_RECOVERY_AFFECTED_BY_HASTE_REGEN,
    IGNORE_DUAL_WIELD_HIT_PENALTY,
    IGNORE_MOVEMENT_FORCES,
    RESET_COOLDOWNS_ON_DUEL_START,  // NYI
    SPELL_AURA_461,
    MOD_HEALING_AND_ABSORB_FROM_CASTER,  // NYI
    CONVERT_CRIT_RATING_PCT_TO_PARRY_RATING,  // NYI
    MOD_ATTACK_POWER_OF_BONUS_ARMOR,  // NYI
    MOD_BONUS_ARMOR,
    MOD_BONUS_ARMOR_PCT,  // Affects bonus armor gain from all sources except base stats
    MOD_STAT_BONUS_PCT,  // Affects stat gain from all sources except base stats
    TRIGGER_SPELL_ON_HEALTH_PCT,  // Triggers spell when health goes above (MiscA ) or falls below (MiscA ) specified percent value (once, not every time condition has meet)
    SHOW_CONFIRMATION_PROMPT_WITH_DIFFICULTY,
    MOD_AURA_TIME_RATE_BY_SPELL_LABEL,  // NYI
    MOD_VERSATILITY,
    SPELL_AURA_472,
    PREVENT_DURABILITY_LOSS_FROM_COMBAT,  // Prevents durability loss from dealing/taking damage
    REPLACE_ITEM_BONUS_TREE,  // NYI
    ALLOW_USING_GAMEOBJECTS_WHILE_MOUNTED,
    MOD_CURRENCY_GAIN_LOOTED,
    SPELL_AURA_477,
    SPELL_AURA_478,
    SPELL_AURA_479,
    MOD_ARTIFACT_ITEM_LEVEL,
    CONVERT_CONSUMED_RUNE,
    SPELL_AURA_482,
    SUPPRESS_TRANSFORMS,  // NYI
    ALLOW_INTERRUPT_SPELL,
    MOD_MOVEMENT_FORCE_MAGNITUDE,
    SPELL_AURA_486,
    COSMETIC_MOUNTED,
    DISABLE_GRAVITY,
    MOD_ALTERNATIVE_DEFAULT_LANGUAGE,
    SPELL_AURA_490,
    SPELL_AURA_491,
    SPELL_AURA_492,
    SPELL_AURA_493, // 1 spell, 267116 - Animal Companion (modifies Call Pet)
    SET_POWER_POINT_CHARGE, // NYI
    TRIGGER_SPELL_ON_EXPIRE,
    ALLOW_CHANGING_EQUIPMENT_IN_TORGHAST, // NYI
    MOD_ANIMA_GAIN, // NYI
    CURRENCY_LOSS_PCT_ON_DEATH, // NYI
    MOD_RESTED_XP_CONSUMPTION,
    IGNORE_SPELL_CHARGE_COOLDOWN,
    MOD_CRITICAL_DAMAGE_TAKEN_FROM_CASTER,
    MOD_VERSATILITY_DAMAGE_DONE_BENEFIT, // NYI
    MOD_VERSATILITY_HEALING_DONE_BENEFIT, // NYI
    MOD_HEALING_TAKEN_FROM_CASTER,
    MOD_PLAYER_CHOICE_REROLLS, // NYI
    DISABLE_INERTIA,
    MOD_DAMAGE_TAKEN_BY_LABEL,
    SPELL_AURA_508,
    SPELL_AURA_509,
    MODIFIED_RAID_INSTANCE, // NYI; Related to "Fated" raid affixes
    APPLY_PROFESSION_EFFECT, // NYI; MiscValue[0] = ProfessionEffectID
    CONVERT_RUNE,
    SPELL_AURA_513,
    SPELL_AURA_514,
    SPELL_AURA_515,
    SPELL_AURA_516,
    SPELL_AURA_517,
    SPELL_AURA_518,
    MOD_COOLDOWN_RECOVERY_RATE_ALL, // NYI; applies to all spells, not filtered by familyflags or label
    SPELL_AURA_520,
    SPELL_AURA_521,
    SPELL_AURA_522,
    SPELL_AURA_523,
    SPELL_AURA_524,
    DISPLAY_PROFESSION_EQUIPMENT, // NYI; MiscValue[0] = Profession (enum, not id)
    SPELL_AURA_526,
    SPELL_AURA_527,
    ALLOW_BLOCKING_SPELLS, // NYI
    MOD_SPELL_BLOCK_CHANCE, // NYI
    SPELL_AURA_530,
    SPELL_AURA_531,
    SPELL_AURA_532,
    DISABLE_NAVIGATION, // disables map pins
    SPELL_AURA_534,
    SPELL_AURA_535, // related to profession equipment; NYI; MiscValue[0] = Profession (enum, not id)
    IGNORE_SPELL_CREATURE_TYPE_REQUIREMENTS,
    MOD_SPELL_DAMAGE_FROM_CASTER_BY_LABEL,
    MOD_FAKE_INEBRIATION_MOVEMENT_ONLY,
    ALLOW_MOUNT_IN_COMBAT,
    MOD_SUPPORT_STAT, // NYI
    MOD_REQUIRED_MOUNT_CAPABILITY_FLAGS,
    TRIGGER_SPELL_ON_STACK_AMOUNT,
    SPELL_AURA_543,
    SPELL_AURA_544,
    SPELL_AURA_545, // prevent swim
    SPELL_AURA_546,
    SPELL_AURA_547,
    MOD_RUNE_REGEN_SPEED,
    SPELL_AURA_549, // formerly SPELL_AURA_46 - Ignore all gear test spells
    SPELL_AURA_550,
    EXTRA_ATTACKS, // NYI
    MOD_SPELL_CRIT_CHANCE_SCHOOL,
    MOD_POWER_COST_SCHOOL,
    SPELL_AURA_554,
    SPELL_AURA_555,
    MOD_MELEE_DAMAGE_TAKEN,
    SPELL_AURA_557,
    MOD_RESISTANCE_EXCLUSIVE, // NYI
    MOD_PET_TALENT_POINTS, // NYI
    RETAIN_COMBO_POINTS, // NYI
    MOD_SHIELD_BLOCKVALUE_PCT,
    SPELL_AURA_562,
    PET_DAMAGE_MULTI, // NYI
    MOD_SHIELD_BLOCKVALUE,
    SPELL_AURA_565,
    MELEE_ATTACK_POWER_ATTACKER_BONUS, // old SPELL_AURA_165 in 4.3.4.15595
    SPELL_AURA_567,
    SPELL_AURA_568,
    MOD_ATTACKER_SPELL_CRIT_CHANCE, // NYI
    SPELL_AURA_570,
    MOD_RESISTANCE_OF_STAT_PERCENT, // NYI
    MOD_CRITICAL_THREAT, // NYI
    MOD_ATTACKER_RANGED_CRIT_CHANCE, // NYI
    MOD_TARGET_ABILITY_ABSORB_SCHOOL, // NYI
    SPELL_AURA_575,
    SPELL_AURA_576,
    MOD_ATTACKER_MELEE_CRIT_DAMAGE, // NYI
    MOD_ATTACKER_RANGED_CRIT_DAMAGE, // NYI
    MOD_SCHOOL_CRIT_DMG_TAKEN, // NYI
    SPELL_AURA_580,
    SPELL_AURA_581,
    SPELL_AURA_582,
    MOD_RATING_FROM_STAT, // NYI
    SPELL_AURA_584, // old SPELL_AURA_222 in 4.3.4.15595
    RAID_PROC_FROM_CHARGE, // NYI
    SPELL_AURA_586,
    SPELL_AURA_587,
    MOD_DISPEL_RESIST, // NYI
    MOD_SPELL_DAMAGE_OF_ATTACK_POWER, // NYI
    MOD_SPELL_HEALING_OF_ATTACK_POWER, // NYI
    MOD_SCALE_2,
    SPELL_AURA_592,
    MOD_COMBAT_RESULT_CHANCE,
    MOD_TARGET_RESIST_BY_SPELL_CLASS,
    SPELL_AURA_595, // old SPELL_AURA_258 in 4.3.4.15595
    SPELL_AURA_596,
    SPELL_AURA_597,
    SPELL_AURA_598,
    MOD_IGNORE_TARGET_RESIST,
    SPELL_AURA_600,
    IGNORE_MELEE_RESET, // NYI
    SPELL_AURA_602,
    SPELL_AURA_603,
    MOD_HONOR_GAIN_PCT,
    SPELL_AURA_605,
    MOD_BASE_HEALTH_PCT,
    MOD_ATTACK_POWER_OF_ARMOR, // NYI
    ABILITY_PERIODIC_CRIT, // NYI
    SPELL_AURA_609,
    SPELL_AURA_610,
    SPELL_AURA_611,
    SPELL_AURA_612,
    SPELL_AURA_613,
    SPELL_AURA_614,
    MOD_RANGED_HASTE_2, // NYI
    SPELL_AURA_616,
    SPELL_AURA_617, // old SPELL_AURA_324 in 4.3.4.15595 - crit chance related
    SPELL_AURA_618,
    MOD_BLIND, // NYI
    MOD_VENDOR_ITEMS_PRICES,
    INCREASE_SKILL_GAIN_CHANCE, // NYI
    MOD_SPELL_COOLDOWN_BY_HASTE,
    MOD_GATHERING_ITEMS_GAINED_PERCENT, // NYI
    MOD_DAMAGE_FROM_MANA, // NYI
    TOTAL_AURAS,
    SPELL_AURA_ANY
}
