package com.github.azeroth.game.entity.player.enums;

public enum TalentLearnResult {
    LEARN_OK,
    FAILED_UNKNOWN,
    FAILED_NOT_ENOUGH_TALENTS_IN_PRIMARY_TREE,
    FAILED_NO_PRIMARY_TREE_SELECTED,
    FAILED_CANT_DO_THAT_RIGHT_NOW,
    FAILED_AFFECTING_COMBAT,
    FAILED_CANT_REMOVE_TALENT,
    FAILED_CANT_DO_THAT_CHALLENGE_MODE_ACTIVE,
    FAILED_REST_AREA
}
