package com.github.azeroth.auth.dto;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum RBACPermissions {

    INSTANT_LOGOUT                                 (1),
    SKIP_QUEUE                                     (2),
    JOIN_NORMAL_BG                                 (3),
    JOIN_RANDOM_BG                                 (4),
    JOIN_ARENAS                                    (5),
    JOIN_DUNGEON_FINDER                            (6),
    IGNORE_IDLE_CONNECTION                         (7),
    CANNOT_EARN_ACHIEVEMENTS                       (8),
    CANNOT_EARN_REALM_FIRST_ACHIEVEMENTS           (9),
    USE_CHARACTER_TEMPLATES                        (10),
    LOG_GM_TRADE                                   (11),
    // 12 previously used, do not reuse
    SKIP_CHECK_INSTANCE_REQUIRED_BOSSES            (13),
    SKIP_CHECK_CHARACTER_CREATION_TEAMMASK         (14),
    SKIP_CHECK_CHARACTER_CREATION_CLASSMASK        (15),
    SKIP_CHECK_CHARACTER_CREATION_RACEMASK         (16),
    SKIP_CHECK_CHARACTER_CREATION_RESERVEDNAME     (17),
    SKIP_CHECK_CHARACTER_CREATION_DEATH_KNIGHT     (18),  // deprecated since Draenor DON'T reuse
    SKIP_CHECK_CHAT_CHANNEL_REQ                    (19),
    SKIP_CHECK_DISABLE_MAP                         (20),
    SKIP_CHECK_MORE_TALENTS_THAN_ALLOWED           (21),
    SKIP_CHECK_CHAT_SPAM                           (22),
    SKIP_CHECK_OVERSPEED_PING                      (23),
    TWO_SIDE_CHARACTER_CREATION                    (24),
    TWO_SIDE_INTERACTION_CHAT                      (25),
    TWO_SIDE_INTERACTION_CHANNEL                   (26),
    TWO_SIDE_INTERACTION_MAIL                      (27),
    TWO_SIDE_WHO_LIST                              (28),
    TWO_SIDE_ADD_FRIEND                            (29),
    COMMANDS_SAVE_WITHOUT_DELAY                    (30),
    COMMANDS_USE_UNSTUCK_WITH_ARGS                 (31),
    COMMANDS_BE_ASSIGNED_TICKET                    (32),
    COMMANDS_NOTIFY_COMMAND_NOT_FOUND_ERROR        (33),
    COMMANDS_APPEAR_IN_GM_LIST                     (34),
    WHO_SEE_ALL_SEC_LEVELS                         (35),
    CAN_FILTER_WHISPERS                            (36),
    CHAT_USE_STAFF_BADGE                           (37),
    RESURRECT_WITH_FULL_HPS                        (38),
    RESTORE_SAVED_GM_STATE                         (39),
    ALLOW_GM_FRIEND                                (40),
    USE_START_GM_LEVEL                             (41),
    OPCODE_WORLD_TELEPORT                          (42),
    OPCODE_WHOIS                                   (43),
    RECEIVE_GLOBAL_GM_TEXTMESSAGE                  (44),
    SILENTLY_JOIN_CHANNEL                          (45),
    CHANGE_CHANNEL_NOT_MODERATOR                   (46),
    CHECK_FOR_LOWER_SECURITY                       (47),
    COMMANDS_PINFO_CHECK_PERSONAL_DATA             (48),
    EMAIL_CONFIRM_FOR_PASS_CHANGE                  (49),
    MAY_CHECK_OWN_EMAIL                            (50),
    ALLOW_TWO_SIDE_TRADE                           (51),

    // Free space for core permissions (till 149)
    // Roles (Permissions with delegated permissions) use 199 and descending

    RBAC_ROLE_ADMINISTRATOR                                  (196),
    RBAC_ROLE_GAMEMASTER                                     (197),
    RBAC_ROLE_MODERATOR                                      (198),
    RBAC_ROLE_PLAYER                                         (199),

    // 200 previously used, do not reuse
    // 201 previously used, do not reuse
    COMMAND_RBAC_ACC_PERM_LIST                     (202),
    COMMAND_RBAC_ACC_PERM_GRANT                    (203),
    COMMAND_RBAC_ACC_PERM_DENY                     (204),
    COMMAND_RBAC_ACC_PERM_REVOKE                   (205),
    COMMAND_RBAC_LIST                              (206),
    COMMAND_BNET_ACCOUNT                           (207),
    COMMAND_BNET_ACCOUNT_CREATE                    (208),
    COMMAND_BNET_ACCOUNT_LOCK_COUNTRY              (209),
    COMMAND_BNET_ACCOUNT_LOCK_IP                   (210),
    COMMAND_BNET_ACCOUNT_PASSWORD                  (211),
    // 212 previously used, do not reuse
    COMMAND_BNET_ACCOUNT_SET_PASSWORD              (213),
    COMMAND_BNET_ACCOUNT_LINK                      (214),
    COMMAND_BNET_ACCOUNT_UNLINK                    (215),
    COMMAND_BNET_ACCOUNT_CREATE_GAME               (216),
    COMMAND_ACCOUNT                                (217),
    COMMAND_ACCOUNT_ADDON                          (218),
    COMMAND_ACCOUNT_CREATE                         (219),
    COMMAND_ACCOUNT_DELETE                         (220),
    COMMAND_ACCOUNT_LOCK                           (221),
    COMMAND_ACCOUNT_LOCK_COUNTRY                   (222),
    COMMAND_ACCOUNT_LOCK_IP                        (223),
    COMMAND_ACCOUNT_ONLINE_LIST                    (224),
    COMMAND_ACCOUNT_PASSWORD                       (225),
    COMMAND_ACCOUNT_SET                            (226),
    COMMAND_ACCOUNT_SET_ADDON                      (227),
    COMMAND_ACCOUNT_SET_SECLEVEL                   (228),
    COMMAND_ACCOUNT_SET_PASSWORD                   (229),
    // 230 previously used, do not reuse
    COMMAND_ACHIEVEMENT_ADD                        (231),
    // 232 previously used, do not reuse
    COMMAND_ARENA_CAPTAIN                          (233),
    COMMAND_ARENA_CREATE                           (234),
    COMMAND_ARENA_DISBAND                          (235),
    COMMAND_ARENA_INFO                             (236),
    COMMAND_ARENA_LOOKUP                           (237),
    COMMAND_ARENA_RENAME                           (238),
    // 239 previously used, do not reuse
    COMMAND_BAN_ACCOUNT                            (240),
    COMMAND_BAN_CHARACTER                          (241),
    COMMAND_BAN_IP                                 (242),
    COMMAND_BAN_PLAYERACCOUNT                      (243),
    // 244 previously used, do not reuse
    COMMAND_BANINFO_ACCOUNT                        (245),
    COMMAND_BANINFO_CHARACTER                      (246),
    COMMAND_BANINFO_IP                             (247),
    // 248 previously used, do not reuse
    COMMAND_BANLIST_ACCOUNT                        (249),
    COMMAND_BANLIST_CHARACTER                      (250),
    COMMAND_BANLIST_IP                             (251),
    // 252 previously used, do not reuse
    COMMAND_UNBAN_ACCOUNT                          (253),
    COMMAND_UNBAN_CHARACTER                        (254),
    COMMAND_UNBAN_IP                               (255),
    COMMAND_UNBAN_PLAYERACCOUNT                    (256),
    // 257 previously used, do not reuse
    COMMAND_BF_START                               (258),
    COMMAND_BF_STOP                                (259),
    COMMAND_BF_SWITCH                              (260),
    COMMAND_BF_TIMER                               (261),
    COMMAND_BF_ENABLE                              (262),
    COMMAND_ACCOUNT_EMAIL                          (263),
    // 264 previously used, do not reuse
    COMMAND_ACCOUNT_SET_SEC_EMAIL                  (265),
    COMMAND_ACCOUNT_SET_SEC_REGMAIL                (266),
    COMMAND_CAST                                   (267),
    COMMAND_CAST_BACK                              (268),
    COMMAND_CAST_DIST                              (269),
    COMMAND_CAST_SELF                              (270),
    COMMAND_CAST_TARGET                            (271),
    COMMAND_CAST_DEST                              (272),
    // 273 previously used, do not reuse
    COMMAND_CHARACTER_CUSTOMIZE                    (274),
    COMMAND_CHARACTER_CHANGEFACTION                (275),
    COMMAND_CHARACTER_CHANGERACE                   (276),
    // 277 previously used, do not reuse
    COMMAND_CHARACTER_DELETED_DELETE               (278),
    COMMAND_CHARACTER_DELETED_LIST                 (279),
    COMMAND_CHARACTER_DELETED_RESTORE              (280),
    COMMAND_CHARACTER_DELETED_OLD                  (281),
    COMMAND_CHARACTER_ERASE                        (282),
    COMMAND_CHARACTER_LEVEL                        (283),
    COMMAND_CHARACTER_RENAME                       (284),
    COMMAND_CHARACTER_REPUTATION                   (285),
    COMMAND_CHARACTER_TITLES                       (286),
    COMMAND_LEVELUP                                (287),
    // 288 previously used, do not reuse
    COMMAND_PDUMP_LOAD                             (289),
    COMMAND_PDUMP_WRITE                            (290),
    // 291 previously used, do not reuse
    COMMAND_CHEAT_CASTTIME                         (292),
    COMMAND_CHEAT_COOLDOWN                         (293),
    COMMAND_CHEAT_EXPLORE                          (294),
    COMMAND_CHEAT_GOD                              (295),
    COMMAND_CHEAT_POWER                            (296),
    COMMAND_CHEAT_STATUS                           (297),
    COMMAND_CHEAT_TAXI                             (298),
    COMMAND_CHEAT_WATERWALK                        (299),
    COMMAND_DEBUG                                  (300),
    // 301-342 previously used, do not reuse
    COMMAND_DESERTER_BG_ADD                        (343),
    COMMAND_DESERTER_BG_REMOVE                     (344),
    // 345 previously used, do not reuse
    COMMAND_DESERTER_INSTANCE_ADD                  (346),
    COMMAND_DESERTER_INSTANCE_REMOVE               (347),
    // 348-349 previously used, do not reuse
    COMMAND_DISABLE_ADD_CRITERIA                   (350),
    COMMAND_DISABLE_ADD_BATTLEGROUND               (351),
    COMMAND_DISABLE_ADD_MAP                        (352),
    COMMAND_DISABLE_ADD_MMAP                       (353),
    COMMAND_DISABLE_ADD_OUTDOORPVP                 (354),
    COMMAND_DISABLE_ADD_QUEST                      (355),
    COMMAND_DISABLE_ADD_SPELL                      (356),
    COMMAND_DISABLE_ADD_VMAP                       (357),
    // 358 previously used, do not reuse
    COMMAND_DISABLE_REMOVE_CRITERIA                (359),
    COMMAND_DISABLE_REMOVE_BATTLEGROUND            (360),
    COMMAND_DISABLE_REMOVE_MAP                     (361),
    COMMAND_DISABLE_REMOVE_MMAP                    (362),
    COMMAND_DISABLE_REMOVE_OUTDOORPVP              (363),
    COMMAND_DISABLE_REMOVE_QUEST                   (364),
    COMMAND_DISABLE_REMOVE_SPELL                   (365),
    COMMAND_DISABLE_REMOVE_VMAP                    (366),
    COMMAND_EVENT_INFO                             (367),
    COMMAND_EVENT_ACTIVELIST                       (368),
    COMMAND_EVENT_START                            (369),
    COMMAND_EVENT_STOP                             (370),
    COMMAND_GM                                     (371),
    COMMAND_GM_CHAT                                (372),
    COMMAND_GM_FLY                                 (373),
    COMMAND_GM_INGAME                              (374),
    COMMAND_GM_LIST                                (375),
    COMMAND_GM_VISIBLE                             (376),
    COMMAND_GO                                     (377),
    COMMAND_ACCOUNT_2FA                            (378),
    COMMAND_ACCOUNT_2FA_SETUP                      (379),
    COMMAND_ACCOUNT_2FA_REMOVE                     (380),
    COMMAND_ACCOUNT_SET_2FA                        (381),
    //                                                       = 382, // DEPRECATED: DON'T REUSE
    //                                                       = 383, // DEPRECATED: DON'T REUSE
    //                                                       = 384, // DEPRECATED: DON'T REUSE
    //                                                       = 385, // DEPRECATED: DON'T REUSE
    //                                                       = 386, // DEPRECATED: DON'T REUSE
    // 387 previously used, do not reuse
    COMMAND_GOBJECT_ACTIVATE                       (388),
    COMMAND_GOBJECT_ADD                            (389),
    COMMAND_GOBJECT_ADD_TEMP                       (390),
    COMMAND_GOBJECT_DELETE                         (391),
    COMMAND_GOBJECT_INFO                           (392),
    COMMAND_GOBJECT_MOVE                           (393),
    COMMAND_GOBJECT_NEAR                           (394),
    // 395 previously used, do not reuse
    COMMAND_GOBJECT_SET_PHASE                      (396),
    COMMAND_GOBJECT_SET_STATE                      (397),
    COMMAND_GOBJECT_TARGET                         (398),
    COMMAND_GOBJECT_TURN                           (399),
    // 400 previously used, do not reuse
    COMMAND_GUILD                                  (401),
    COMMAND_GUILD_CREATE                           (402),
    COMMAND_GUILD_DELETE                           (403),
    COMMAND_GUILD_INVITE                           (404),
    COMMAND_GUILD_UNINVITE                         (405),
    COMMAND_GUILD_RANK                             (406),
    COMMAND_GUILD_RENAME                           (407),
    // 408 previously used, do not reuse
    COMMAND_HONOR_ADD                              (409),
    COMMAND_HONOR_ADD_KILL                         (410),
    COMMAND_HONOR_UPDATE                           (411),
    // 412 previously used, do not reuse
    COMMAND_INSTANCE_LISTBINDS                     (413),
    COMMAND_INSTANCE_UNBIND                        (414),
    COMMAND_INSTANCE_STATS                         (415),
    // 416 previously used, do not reuse
    COMMAND_LEARN                                  (417),
    // 418 previously used, do not reuse
    COMMAND_LEARN_ALL_MY                           (419),
    COMMAND_LEARN_ALL_MY_CLASS                     (420),
    COMMAND_LEARN_MY_PETTALENTS                    (421),
    COMMAND_LEARN_ALL_MY_SPELLS                    (422),
    COMMAND_LEARN_ALL_TALENTS                      (423),
    COMMAND_LEARN_ALL_GM                           (424),
    COMMAND_LEARN_ALL_CRAFTS                       (425),
    COMMAND_LEARN_ALL_DEFAULT                      (426),
    COMMAND_LEARN_ALL_LANG                         (427),
    COMMAND_LEARN_ALL_RECIPES                      (428),
    COMMAND_UNLEARN                                (429),
    // 430 previously used, do not reuse
    COMMAND_LFG_PLAYER                             (431),
    COMMAND_LFG_GROUP                              (432),
    COMMAND_LFG_QUEUE                              (433),
    COMMAND_LFG_CLEAN                              (434),
    COMMAND_LFG_OPTIONS                            (435),
    // 436 previously used, do not reuse
    COMMAND_LIST_CREATURE                          (437),
    COMMAND_LIST_ITEM                              (438),
    COMMAND_LIST_OBJECT                            (439),
    COMMAND_LIST_AURAS                             (440),
    COMMAND_LIST_MAIL                              (441),
    COMMAND_LOOKUP                                 (442),
    COMMAND_LOOKUP_AREA                            (443),
    COMMAND_LOOKUP_CREATURE                        (444),
    COMMAND_LOOKUP_EVENT                           (445),
    COMMAND_LOOKUP_FACTION                         (446),
    COMMAND_LOOKUP_ITEM                            (447),
    COMMAND_LOOKUP_ITEMSET                         (448),
    COMMAND_LOOKUP_OBJECT                          (449),
    COMMAND_LOOKUP_QUEST                           (450),
    COMMAND_LOOKUP_PLAYER                          (451),
    COMMAND_LOOKUP_PLAYER_IP                       (452),
    COMMAND_LOOKUP_PLAYER_ACCOUNT                  (453),
    COMMAND_LOOKUP_PLAYER_EMAIL                    (454),
    COMMAND_LOOKUP_SKILL                           (455),
    COMMAND_LOOKUP_SPELL                           (456),
    COMMAND_LOOKUP_SPELL_ID                        (457),
    COMMAND_LOOKUP_TAXINODE                        (458),
    COMMAND_LOOKUP_TELE                            (459),
    COMMAND_LOOKUP_TITLE                           (460),
    COMMAND_LOOKUP_MAP                             (461),
    COMMAND_ANNOUNCE                               (462),
    COMMAND_CHANNEL                                (463),
    COMMAND_CHANNEL_SET                            (464),
    COMMAND_CHANNEL_SET_OWNERSHIP                  (465),
    COMMAND_GMANNOUNCE                             (466),
    COMMAND_GMNAMEANNOUNCE                         (467),
    COMMAND_GMNOTIFY                               (468),
    COMMAND_NAMEANNOUNCE                           (469),
    COMMAND_NOTIFY                                 (470),
    COMMAND_WHISPERS                               (471),
    COMMAND_GROUP                                  (472),
    COMMAND_GROUP_LEADER                           (473),
    COMMAND_GROUP_DISBAND                          (474),
    COMMAND_GROUP_REMOVE                           (475),
    COMMAND_GROUP_JOIN                             (476),
    COMMAND_GROUP_LIST                             (477),
    COMMAND_GROUP_SUMMON                           (478),
    COMMAND_PET                                    (479),
    COMMAND_PET_CREATE                             (480),
    COMMAND_PET_LEARN                              (481),
    COMMAND_PET_UNLEARN                            (482),
    COMMAND_SEND                                   (483),
    COMMAND_SEND_ITEMS                             (484),
    COMMAND_SEND_MAIL                              (485),
    COMMAND_SEND_MESSAGE                           (486),
    COMMAND_SEND_MONEY                             (487),
    COMMAND_ADDITEM                                (488),
    COMMAND_ADDITEMSET                             (489),
    COMMAND_APPEAR                                 (490),
    COMMAND_AURA                                   (491),
    COMMAND_BANK                                   (492),
    COMMAND_BINDSIGHT                              (493),
    COMMAND_COMBATSTOP                             (494),
    COMMAND_COMETOME                               (495),
    COMMAND_COMMANDS                               (496),
    COMMAND_COOLDOWN                               (497),
    COMMAND_DAMAGE                                 (498),
    COMMAND_DEV                                    (499),
    COMMAND_DIE                                    (500),
    COMMAND_DISMOUNT                               (501),
    COMMAND_DISTANCE                               (502),
    COMMAND_FLUSHARENAPOINTS                       (503),
    COMMAND_FREEZE                                 (504),
    COMMAND_GPS                                    (505),
    COMMAND_GUID                                   (506),
    COMMAND_HELP                                   (507),
    COMMAND_HIDEAREA                               (508),
    COMMAND_ITEMMOVE                               (509),
    COMMAND_KICK                                   (510),
    COMMAND_LINKGRAVE                              (511),
    COMMAND_LISTFREEZE                             (512),
    COMMAND_MAXSKILL                               (513), // DEPRECATED: DON'T REUSE
    COMMAND_MOVEGENS                               (514),
    COMMAND_MUTE                                   (515),
    COMMAND_NEARGRAVE                              (516),
    COMMAND_PINFO                                  (517),
    COMMAND_PLAYALL                                (518),
    COMMAND_POSSESS                                (519),
    COMMAND_RECALL                                 (520),
    COMMAND_REPAIRITEMS                            (521),
    COMMAND_RESPAWN                                (522),
    COMMAND_REVIVE                                 (523),
    COMMAND_SAVEALL                                (524),
    COMMAND_SAVE                                   (525),
    COMMAND_SETSKILL                               (526),
    COMMAND_SHOWAREA                               (527),
    COMMAND_SUMMON                                 (528),
    COMMAND_UNAURA                                 (529),
    COMMAND_UNBINDSIGHT                            (530),
    COMMAND_UNFREEZE                               (531),
    COMMAND_UNMUTE                                 (532),
    COMMAND_UNPOSSESS                              (533),
    COMMAND_UNSTUCK                                (534),
    COMMAND_WCHANGE                                (535),
    COMMAND_MMAP                                   (536),
    COMMAND_MMAP_LOADEDTILES                       (537),
    COMMAND_MMAP_LOC                               (538),
    COMMAND_MMAP_PATH                              (539),
    COMMAND_MMAP_STATS                             (540),
    COMMAND_MMAP_TESTAREA                          (541),
    COMMAND_MORPH                                  (542),
    COMMAND_DEMORPH                                (543),
    COMMAND_MODIFY                                 (544),
    COMMAND_MODIFY_ARENAPOINTS                     (545),
    COMMAND_MODIFY_BIT                             (546), // DEPRECATED: DON'T REUSE
    COMMAND_MODIFY_DRUNK                           (547),
    COMMAND_MODIFY_ENERGY                          (548),
    COMMAND_MODIFY_FACTION                         (549),
    COMMAND_MODIFY_GENDER                          (550),
    COMMAND_MODIFY_HONOR                           (551),
    COMMAND_MODIFY_HP                              (552),
    COMMAND_MODIFY_MANA                            (553),
    COMMAND_MODIFY_MONEY                           (554),
    COMMAND_MODIFY_MOUNT                           (555),
    COMMAND_MODIFY_PHASE                           (556),
    COMMAND_MODIFY_RAGE                            (557),
    COMMAND_MODIFY_REPUTATION                      (558),
    COMMAND_MODIFY_RUNICPOWER                      (559),
    COMMAND_MODIFY_SCALE                           (560),
    COMMAND_MODIFY_SPEED                           (561),
    COMMAND_MODIFY_SPEED_ALL                       (562),
    COMMAND_MODIFY_SPEED_BACKWALK                  (563),
    COMMAND_MODIFY_SPEED_FLY                       (564),
    COMMAND_MODIFY_SPEED_WALK                      (565),
    COMMAND_MODIFY_SPEED_SWIM                      (566),
    COMMAND_MODIFY_SPELL                           (567),
    COMMAND_MODIFY_STANDSTATE                      (568),
    COMMAND_MODIFY_TALENTPOINTS                    (569),
    // 570 previously used, do not reuse
    COMMAND_NPC_ADD                                (571),
    COMMAND_NPC_ADD_FORMATION                      (572),
    COMMAND_NPC_ADD_ITEM                           (573),
    COMMAND_NPC_ADD_MOVE                           (574),
    COMMAND_NPC_ADD_TEMP                           (575),
    COMMAND_NPC_DELETE                             (576),
    COMMAND_NPC_DELETE_ITEM                        (577),
    COMMAND_NPC_FOLLOW                             (578),
    COMMAND_NPC_FOLLOW_STOP                        (579),
    COMMAND_NPC_SET                                (580),
    COMMAND_NPC_SET_ALLOWMOVE                      (581),
    COMMAND_NPC_SET_ENTRY                          (582),
    COMMAND_NPC_SET_FACTIONID                      (583),
    COMMAND_NPC_SET_FLAG                           (584),
    COMMAND_NPC_SET_LEVEL                          (585),
    COMMAND_NPC_SET_LINK                           (586),
    COMMAND_NPC_SET_MODEL                          (587),
    COMMAND_NPC_SET_MOVETYPE                       (588),
    COMMAND_NPC_SET_PHASE                          (589),
    COMMAND_NPC_SET_SPAWNDIST                      (590),
    COMMAND_NPC_SET_SPAWNTIME                      (591),
    COMMAND_NPC_SET_DATA                           (592),
    COMMAND_NPC_INFO                               (593),
    COMMAND_NPC_NEAR                               (594),
    COMMAND_NPC_MOVE                               (595),
    COMMAND_NPC_PLAYEMOTE                          (596),
    COMMAND_NPC_SAY                                (597),
    COMMAND_NPC_TEXTEMOTE                          (598),
    COMMAND_NPC_WHISPER                            (599),
    COMMAND_NPC_YELL                               (600),
    COMMAND_NPC_TAME                               (601),
    COMMAND_QUEST                                  (602),
    COMMAND_QUEST_ADD                              (603),
    COMMAND_QUEST_COMPLETE                         (604),
    COMMAND_QUEST_REMOVE                           (605),
    COMMAND_QUEST_REWARD                           (606),
    COMMAND_RELOAD                                 (607),
    COMMAND_RELOAD_ACCESS_REQUIREMENT              (608),
    COMMAND_RELOAD_CRITERIA_DATA                   (609),
    COMMAND_RELOAD_ACHIEVEMENT_REWARD              (610),
    COMMAND_RELOAD_ALL                             (611),
    COMMAND_RELOAD_ALL_ACHIEVEMENT                 (612),
    COMMAND_RELOAD_ALL_AREA                        (613),
    COMMAND_RELOAD_BROADCAST_TEXT                  (614),
    COMMAND_RELOAD_ALL_GOSSIP                      (615),
    COMMAND_RELOAD_ALL_ITEM                        (616),
    COMMAND_RELOAD_ALL_LOCALES                     (617),
    COMMAND_RELOAD_ALL_LOOT                        (618),
    COMMAND_RELOAD_ALL_NPC                         (619),
    COMMAND_RELOAD_ALL_QUEST                       (620),
    COMMAND_RELOAD_ALL_SCRIPTS                     (621),
    COMMAND_RELOAD_ALL_SPELL                       (622),
    COMMAND_RELOAD_AREATRIGGER_INVOLVEDRELATION    (623),
    COMMAND_RELOAD_AREATRIGGER_TAVERN              (624),
    COMMAND_RELOAD_AREATRIGGER_TELEPORT            (625),
    COMMAND_RELOAD_AUCTIONS                        (626),
    COMMAND_RELOAD_AUTOBROADCAST                   (627),
    // 628 previously used, do not reuse
    COMMAND_RELOAD_CONDITIONS                      (629),
    COMMAND_RELOAD_CONFIG                          (630),
    COMMAND_RELOAD_BATTLEGROUND_TEMPLATE           (631),
    COMMAND_MUTEHISTORY                            (632),
    COMMAND_RELOAD_CREATURE_LINKED_RESPAWN         (633),
    COMMAND_RELOAD_CREATURE_LOOT_TEMPLATE          (634),
    COMMAND_RELOAD_CREATURE_ONKILL_REPUTATION      (635),
    COMMAND_RELOAD_CREATURE_QUESTENDER             (636),
    COMMAND_RELOAD_CREATURE_QUESTSTARTER           (637),
    COMMAND_RELOAD_CREATURE_SUMMON_GROUPS          (638),
    COMMAND_RELOAD_CREATURE_TEMPLATE               (639),
    COMMAND_RELOAD_CREATURE_TEXT                   (640),
    COMMAND_RELOAD_DISABLES                        (641),
    COMMAND_RELOAD_DISENCHANT_LOOT_TEMPLATE        (642),
    COMMAND_RELOAD_EVENT_SCRIPTS                   (643),
    COMMAND_RELOAD_FISHING_LOOT_TEMPLATE           (644),
    COMMAND_RELOAD_GRAVEYARD_ZONE                  (645),
    COMMAND_RELOAD_GAME_TELE                       (646),
    COMMAND_RELOAD_GAMEOBJECT_QUESTENDER           (647),
    COMMAND_RELOAD_GAMEOBJECT_QUEST_LOOT_TEMPLATE  (648),
    COMMAND_RELOAD_GAMEOBJECT_QUESTSTARTER         (649),
    COMMAND_RELOAD_SUPPORT_SYSTEM                  (650),
    COMMAND_RELOAD_GOSSIP_MENU                     (651),
    COMMAND_RELOAD_GOSSIP_MENU_OPTION              (652),
    COMMAND_RELOAD_ITEM_RANDOM_BONUS_LIST_TEMPLATE (653),
    COMMAND_RELOAD_ITEM_LOOT_TEMPLATE              (654),
    COMMAND_RELOAD_ITEM_SET_NAMES                  (655),
    COMMAND_RELOAD_LFG_DUNGEON_REWARDS             (656),
    COMMAND_RELOAD_ACHIEVEMENT_REWARD_LOCALE       (657),
    COMMAND_RELOAD_CRETURE_TEMPLATE_LOCALE         (658),
    COMMAND_RELOAD_CRETURE_TEXT_LOCALE             (659),
    COMMAND_RELOAD_GAMEOBJECT_TEMPLATE_LOCALE      (660),
    COMMAND_RELOAD_GOSSIP_MENU_OPTION_LOCALE       (661),
    COMMAND_RELOAD_ITEM_TEMPLATE_LOCALE            (662), // deprecated since Draenor DON'T reus
    COMMAND_RELOAD_ITEM_SET_NAME_LOCALE            (663),
    COMMAND_RELOAD_NPC_TEXT_LOCALE                 (664), // deprecated since Draenor DON'T reuse
    COMMAND_RELOAD_PAGE_TEXT_LOCALE                (665),
    COMMAND_RELOAD_POINTS_OF_INTEREST_LOCALE       (666),
    COMMAND_RELOAD_QUEST_TEMPLATE_LOCALE           (667),
    COMMAND_RELOAD_MAIL_LEVEL_REWARD               (668),
    COMMAND_RELOAD_MAIL_LOOT_TEMPLATE              (669),
    COMMAND_RELOAD_MILLING_LOOT_TEMPLATE           (670),
    COMMAND_RELOAD_NPC_SPELLCLICK_SPELLS           (671),
    COMMAND_RELOAD_TRAINER                         (672),
    COMMAND_RELOAD_NPC_VENDOR                      (673),
    COMMAND_RELOAD_PAGE_TEXT                       (674),
    COMMAND_RELOAD_PICKPOCKETING_LOOT_TEMPLATE     (675),
    COMMAND_RELOAD_POINTS_OF_INTEREST              (676),
    COMMAND_RELOAD_PROSPECTING_LOOT_TEMPLATE       (677),
    COMMAND_RELOAD_QUEST_POI                       (678),
    COMMAND_RELOAD_QUEST_TEMPLATE                  (679),
    COMMAND_RELOAD_RBAC                            (680),
    COMMAND_RELOAD_REFERENCE_LOOT_TEMPLATE         (681),
    COMMAND_RELOAD_RESERVED_NAME                   (682),
    COMMAND_RELOAD_REPUTATION_REWARD_RATE          (683),
    COMMAND_RELOAD_SPILLOVER_TEMPLATE              (684),
    COMMAND_RELOAD_SKILL_DISCOVERY_TEMPLATE        (685),
    COMMAND_RELOAD_SKILL_EXTRA_ITEM_TEMPLATE       (686),
    COMMAND_RELOAD_SKILL_FISHING_BASE_LEVEL        (687),
    COMMAND_RELOAD_SKINNING_LOOT_TEMPLATE          (688),
    COMMAND_RELOAD_SMART_SCRIPTS                   (689),
    COMMAND_RELOAD_SPELL_REQUIRED                  (690),
    COMMAND_RELOAD_SPELL_AREA                      (691),
    COMMAND_RELOAD_SPELL_BONUS_DATA                (692), // deprecated since Draenor DON'T reuse
    COMMAND_RELOAD_SPELL_GROUP                     (693),
    COMMAND_RELOAD_SPELL_LEARN_SPELL               (694),
    COMMAND_RELOAD_SPELL_LOOT_TEMPLATE             (695),
    COMMAND_RELOAD_SPELL_LINKED_SPELL              (696),
    COMMAND_RELOAD_SPELL_PET_AURAS                 (697),
    COMMAND_CHARACTER_CHANGEACCOUNT                (698),
    COMMAND_RELOAD_SPELL_PROC                      (699),
    COMMAND_RELOAD_SPELL_SCRIPTS                   (700),
    COMMAND_RELOAD_SPELL_TARGET_POSITION           (701),
    COMMAND_RELOAD_SPELL_THREATS                   (702),
    COMMAND_RELOAD_SPELL_GROUP_STACK_RULES         (703),
    COMMAND_RELOAD_TRINITY_STRING                  (704),
    // 705 previously used, do not reuse                     (   )
    // 706 previously used, do not reuse                     (   )
    COMMAND_RELOAD_WAYPOINT_PATH                   (707),
    COMMAND_RELOAD_VEHICLE_ACCESORY                (708),
    COMMAND_RELOAD_VEHICLE_TEMPLATE_ACCESSORY      (709),
    COMMAND_RESET                                  (710),
    COMMAND_RESET_ACHIEVEMENTS                     (711),
    COMMAND_RESET_HONOR                            (712),
    COMMAND_RESET_LEVEL                            (713),
    COMMAND_RESET_SPELLS                           (714),
    COMMAND_RESET_STATS                            (715),
    COMMAND_RESET_TALENTS                          (716),
    COMMAND_RESET_ALL                              (717),
    COMMAND_SERVER                                 (718),
    COMMAND_SERVER_CORPSES                         (719),
    COMMAND_SERVER_EXIT                            (720),
    COMMAND_SERVER_IDLERESTART                     (721),
    COMMAND_SERVER_IDLERESTART_CANCEL              (722),
    COMMAND_SERVER_IDLESHUTDOWN                    (723),
    COMMAND_SERVER_IDLESHUTDOWN_CANCEL             (724),
    COMMAND_SERVER_INFO                            (725),
    COMMAND_SERVER_PLIMIT                          (726),
    COMMAND_SERVER_RESTART                         (727),
    COMMAND_SERVER_RESTART_CANCEL                  (728),
    COMMAND_SERVER_SET                             (729),
    COMMAND_SERVER_SET_CLOSED                      (730),
    COMMAND_SERVER_SET_DIFFTIME                    (731), // reserved
    COMMAND_SERVER_SET_LOGLEVEL                    (732),
    COMMAND_SERVER_SET_MOTD                        (733),
    COMMAND_SERVER_SHUTDOWN                        (734),
    COMMAND_SERVER_SHUTDOWN_CANCEL                 (735),
    COMMAND_SERVER_MOTD                            (736),
    COMMAND_TELE                                   (737),
    COMMAND_TELE_ADD                               (738),
    COMMAND_TELE_DEL                               (739),
    COMMAND_TELE_NAME                              (740),
    COMMAND_TELE_GROUP                             (741),
    COMMAND_TICKET                                 (742),
    COMMAND_TICKET_ASSIGN                          (743), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_CLOSE                           (744), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_CLOSEDLIST                      (745), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_COMMENT                         (746), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_COMPLETE                        (747), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_DELETE                          (748), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_ESCALATE                        (749), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_ESCALATEDLIST                   (750), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_LIST                            (751), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_ONLINELIST                      (752), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_RESET                           (753),
    COMMAND_TICKET_RESPONSE                        (754), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_RESPONSE_APPEND                 (755), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_RESPONSE_APPENDLN               (756), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_TOGGLESYSTEM                    (757),
    COMMAND_TICKET_UNASSIGN                        (758), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_VIEWID                          (759), // deprecated since Draenor DON'T reuse
    COMMAND_TICKET_VIEWNAME                        (760), // deprecated since Draenor DON'T reuse
    // 761 previously used, do not reuse                     (   )
    COMMAND_TITLES_ADD                             (762),
    COMMAND_TITLES_CURRENT                         (763),
    COMMAND_TITLES_REMOVE                          (764),
    // 765 previously used, do not reuse                     (   )
    COMMAND_TITLES_SET_MASK                        (766),
    COMMAND_WP                                     (767),
    COMMAND_WP_ADD                                 (768),
    COMMAND_WP_EVENT                               (769),
    COMMAND_WP_LOAD                                (770),
    COMMAND_WP_MODIFY                              (771),
    COMMAND_WP_UNLOAD                              (772),
    COMMAND_WP_RELOAD                              (773),
    COMMAND_WP_SHOW                                (774),
    COMMAND_MODIFY_CURRENCY                        (775),
    // 776 previously used, do not reuse                     (   )
    COMMAND_MAILBOX                                (777),
    // 778 previously used, do not reuse                     (   )
    COMMAND_AHBOT_ITEMS                            (779),
    COMMAND_AHBOT_ITEMS_GRAY                       (780),
    COMMAND_AHBOT_ITEMS_WHITE                      (781),
    COMMAND_AHBOT_ITEMS_GREEN                      (782),
    COMMAND_AHBOT_ITEMS_BLUE                       (783),
    COMMAND_AHBOT_ITEMS_PURPLE                     (784),
    COMMAND_AHBOT_ITEMS_ORANGE                     (785),
    COMMAND_AHBOT_ITEMS_YELLOW                     (786),
    COMMAND_AHBOT_RATIO                            (787),
    COMMAND_AHBOT_RATIO_ALLIANCE                   (788),
    COMMAND_AHBOT_RATIO_HORDE                      (789),
    COMMAND_AHBOT_RATIO_NEUTRAL                    (790),
    COMMAND_AHBOT_REBUILD                          (791),
    COMMAND_AHBOT_RELOAD                           (792),
    COMMAND_AHBOT_STATUS                           (793),
    COMMAND_GUILD_INFO                             (794),
    COMMAND_INSTANCE_SET_BOSS_STATE                (795),
    COMMAND_INSTANCE_GET_BOSS_STATE                (796),
    COMMAND_PVPSTATS                               (797),
    COMMAND_MODIFY_XP                              (798),
    //                                                       (799), // DEPRECATED: DON'T REUSE
    //                                                       (800), // DEPRECATED: DON'T REUSE
    //                                                       (801), // DEPRECATED: DON'T REUSE
    COMMAND_TICKET_BUG                             (802),
    COMMAND_TICKET_COMPLAINT                       (803),
    COMMAND_TICKET_SUGGESTION                      (804),
    COMMAND_TICKET_BUG_ASSIGN                      (805),
    COMMAND_TICKET_BUG_CLOSE                       (806),
    COMMAND_TICKET_BUG_CLOSEDLIST                  (807),
    COMMAND_TICKET_BUG_COMMENT                     (808),
    COMMAND_TICKET_BUG_DELETE                      (809),
    COMMAND_TICKET_BUG_LIST                        (810),
    COMMAND_TICKET_BUG_UNASSIGN                    (811),
    COMMAND_TICKET_BUG_VIEW                        (812),
    COMMAND_TICKET_COMPLAINT_ASSIGN                (813),
    COMMAND_TICKET_COMPLAINT_CLOSE                 (814),
    COMMAND_TICKET_COMPLAINT_CLOSEDLIST            (815),
    COMMAND_TICKET_COMPLAINT_COMMENT               (816),
    COMMAND_TICKET_COMPLAINT_DELETE                (817),
    COMMAND_TICKET_COMPLAINT_LIST                  (818),
    COMMAND_TICKET_COMPLAINT_UNASSIGN              (819),
    COMMAND_TICKET_COMPLAINT_VIEW                  (820),
    COMMAND_TICKET_SUGGESTION_ASSIGN               (821),
    COMMAND_TICKET_SUGGESTION_CLOSE                (822),
    COMMAND_TICKET_SUGGESTION_CLOSEDLIST           (823),
    COMMAND_TICKET_SUGGESTION_COMMENT              (824),
    COMMAND_TICKET_SUGGESTION_DELETE               (825),
    COMMAND_TICKET_SUGGESTION_LIST                 (826),
    COMMAND_TICKET_SUGGESTION_UNASSIGN             (827),
    COMMAND_TICKET_SUGGESTION_VIEW                 (828),
    COMMAND_TICKET_RESET_ALL                       (829),
    COMMAND_BNET_ACCOUNT_LIST_GAME_ACCOUTNS        (830),
    COMMAND_TICKET_RESET_BUG                       (831),
    COMMAND_TICKET_RESET_COMPLAINT                 (832),
    COMMAND_TICKET_RESET_SUGGESTION                (833),
    //                                                       = 834, // DEPRECATED: DON'T REUSE
    // 835-836 previously used, do not reuse
    COMMAND_NPC_EVADE                              (837),
    COMMAND_PET_LEVEL                              (838),
    COMMAND_SERVER_SHUTDOWN_FORCE                  (839),
    COMMAND_SERVER_RESTART_FORCE                   (840),
    COMMAND_NEARGRAVEYARD                          (841),
    COMMAND_RELOAD_CHARACTER_TEMPLATE              (842),
    COMMAND_RELOAD_QUEST_GREETING                  (843),
    COMMAND_SCENE                                  (844),
    COMMAND_SCENE_DEBUG                            (845),
    COMMAND_SCENE_PLAY                             (846),
    COMMAND_SCENE_PLAY_PACKAGE                     (847),
    COMMAND_SCENE_CANCEL                           (848),
    COMMAND_LIST_SCENES                            (849),
    COMMAND_RELOAD_SCENE_TEMPLATE                  (850),
    COMMAND_RELOAD_AREATRIGGER_TEMPLATE            (851),
    // 852 previously used, do not reuse
    COMMAND_RELOAD_CONVERSATION_TEMPLATE           (853),
    // 854-855 previously used, do not reuse
    COMMAND_NPC_SPAWNGROUP                         (856),
    COMMAND_NPC_DESPAWNGROUP                       (857),
    COMMAND_GOBJECT_SPAWNGROUP                     (858),
    COMMAND_GOBJECT_DESPAWNGROUP                   (859),
    COMMAND_LIST_RESPAWNS                          (860),
    COMMAND_GROUP_SET                              (861),
    COMMAND_GROUP_ASSISTANT                        (862),
    COMMAND_GROUP_MAINTANK                         (863),
    COMMAND_GROUP_MAINASSIST                       (864),
    COMMAND_NPC_SHOWLOOT                           (865),
    COMMAND_LIST_SPAWNPOINTS                       (866),
    COMMAND_RELOAD_QUEST_GREETING_LOCALE           (867), // reserved
    COMMAND_MODIFY_POWER                           (868),
    // 869 previously used, do not reuse
    // 870-871 previously used, do not reuse
    COMMAND_SERVER_DEBUG                           (872),
    COMMAND_RELOAD_CREATURE_MOVEMENT_OVERRIDE      (873),
    // 874 previously used, do not reuse
    COMMAND_LOOKUP_MAP_ID                          (875),
    COMMAND_LOOKUP_ITEM_ID                         (876),
    COMMAND_LOOKUP_QUEST_ID                        (877),
    // 878-879 previously used, do not reuse
    COMMAND_PDUMP_COPY                             (880),
    COMMAND_RELOAD_VEHICLE_TEMPLATE                (881),
    COMMAND_RELOAD_SPELL_SCRIPT_NAMES              (882),
    COMMAND_QUEST_OBJECTIVE_COMPLETE               (883);
    //
    // IF YOU ADD NEW PERMISSIONS, ADD THEM IN 3.3.5 BRANCH AS WELL!
    //
    // custom permissions 1000+

    public final int id;
}
