package com.github.azeroth.game.networking;

import com.github.azeroth.game.calendar.CalendarInvite;
import com.github.azeroth.game.loot.LootRoll;
import com.github.azeroth.game.networking.opcode.ClientOpCode;
import com.github.azeroth.game.networking.packet.achievement.GuildSetFocusedAchievement;
import com.github.azeroth.game.networking.packet.adventurejournal.AdventureJournalOpenQuest;
import com.github.azeroth.game.networking.packet.adventuremap.AdventureMapStartQuest;
import com.github.azeroth.game.networking.packet.auctionhouse.AuctionBrowseQuery;
import com.github.azeroth.game.networking.packet.auctionhouse.AuctionCancelCommoditiesPurchase;
import com.github.azeroth.game.networking.packet.auctionhouse.AuctionConfirmCommoditiesPurchase;
import com.github.azeroth.game.networking.packet.bank.BuyBankSlot;
import com.github.azeroth.game.networking.packet.battleground.AreaSpiritHealerQuery;
import com.github.azeroth.game.networking.packet.battleground.AreaSpiritHealerQueue;
import com.github.azeroth.game.networking.packet.battleground.HearthAndResurrect;
import com.github.azeroth.game.networking.packet.battlenet.BattlenetRequest;
import com.github.azeroth.game.networking.packet.blackmarket.BlackMarketBidOnItem;
import com.github.azeroth.game.networking.packet.blackmarket.BlackMarketOpen;
import com.github.azeroth.game.networking.packet.blackmarket.BlackMarketRequestItems;
import com.github.azeroth.game.networking.packet.calendar.CalendarCommunityInvite;
import com.github.azeroth.game.networking.packet.calendar.CalendarModeratorStatus;
import com.github.azeroth.game.networking.packet.character.AlterAppearance;
import com.github.azeroth.game.networking.packet.combat.AttackStop;
import com.github.azeroth.game.networking.packet.combat.AttackSwing;
import com.github.azeroth.game.networking.packet.duel.CanDuel;
import com.github.azeroth.game.networking.packet.guild.*;
import com.github.azeroth.game.networking.packet.hotfix.HotfixRequest;
import com.github.azeroth.game.networking.packet.inspect.Inspect;
import com.github.azeroth.game.networking.packet.item.BuyBackItem;
import com.github.azeroth.game.networking.packet.item.BuyItem;
import com.github.azeroth.game.networking.packet.item.WrapItem;
import com.github.azeroth.game.networking.packet.loot.LootUnit;
import com.github.azeroth.game.networking.packet.mail.*;
import com.github.azeroth.game.networking.packet.movement.WorldPortResponse;
import com.github.azeroth.game.networking.packet.party.InitiateRolePoll;
import com.github.azeroth.game.networking.packet.social.AddFriend;
import com.github.azeroth.game.networking.packet.social.AddIgnore;
import com.github.azeroth.game.networking.packet.taxi.ActivateTaxi;
import com.github.azeroth.game.networking.packet.ticket.BugReport;
import com.github.azeroth.game.networking.packet.toy.AddToy;
import com.github.azeroth.game.networking.packet.trade.*;
import io.netty.buffer.ByteBuf;

abstract class ClientPacketFactory {
    public static ClientPacket create(ClientOpCode opCode, ByteBuf byteBuf) {
        return switch (opCode) {
            case CMSG_ACCEPT_TRADE -> new AcceptTrade(byteBuf);
            case CMSG_ACCEPT_GUILD_INVITE -> new AcceptGuildInvite(byteBuf);
            case CMSG_ACCEPT_SOCIAL_CONTRACT -> null;
            case CMSG_ACCEPT_WARGAME_INVITE -> null;
            case CMSG_ACCOUNT_NOTIFICATION_ACKNOWLEDGED -> null;
            case CMSG_ACCOUNT_STORE_BEGIN_PURCHASE_OR_REFUND -> null;
            case CMSG_ACTIVATE_TAXI -> new ActivateTaxi(byteBuf);
            case CMSG_ADD_BATTLENET_FRIEND -> null;
            case CMSG_ADD_FRIEND -> new AddFriend(byteBuf);
            case CMSG_ADD_IGNORE -> new AddIgnore(byteBuf);
            case CMSG_ADD_TOY -> new AddToy(byteBuf);
            case CMSG_ADDON_LIST -> new AddonList();
            case CMSG_ADVENTURE_JOURNAL_OPEN_QUEST -> new AdventureJournalOpenQuest(byteBuf);
            case CMSG_ADVENTURE_MAP_START_QUEST -> new AdventureMapStartQuest(byteBuf);
            case CMSG_ALTER_APPEARANCE -> new AlterAppearance(byteBuf);
            case CMSG_AREA_SPIRIT_HEALER_QUERY -> new AreaSpiritHealerQuery(byteBuf);
            case CMSG_AREA_SPIRIT_HEALER_QUEUE -> new AreaSpiritHealerQueue(byteBuf);
            case CMSG_AREA_TRIGGER -> null;
            case CMSG_ARENA_TEAM_ACCEPT -> new ArenaTeamAccept(byteBuf);
            case CMSG_ARENA_TEAM_DECLINE -> new ArenaTeamDecline(byteBuf);
            case CMSG_ARENA_TEAM_DISBAND -> new ArenaTeamDisband(byteBuf);
            case CMSG_ARENA_TEAM_LEADER -> new ArenaTeamLeader(byteBuf);
            case CMSG_ARENA_TEAM_LEAVE -> new ArenaTeamLeave(byteBuf);
            case CMSG_ARENA_TEAM_REMOVE -> new ArenaTeamRemove(byteBuf);
            case CMSG_ARENA_TEAM_ROSTER -> new ArenaTeamRoster(byteBuf);
            case CMSG_ASSIGN_EQUIPMENT_SET_SPEC -> new AssignEquipmentSetSpec(byteBuf);
            case CMSG_ATTACK_STOP -> new AttackStop(byteBuf);
            case CMSG_ATTACK_SWING -> new AttackSwing(byteBuf);
            case CMSG_AUCTION_BROWSE_QUERY -> new AuctionBrowseQuery(byteBuf);
            case CMSG_AUCTION_CANCEL_COMMODITIES_PURCHASE -> new AuctionCancelCommoditiesPurchase(byteBuf);
            case CMSG_AUCTION_CONFIRM_COMMODITIES_PURCHASE -> new AuctionConfirmCommoditiesPurchase(byteBuf);
            case CMSG_AUCTION_GET_COMMODITY_QUOTE -> new AuctionGetCommodityQuote(byteBuf);
            case CMSG_AUCTION_HELLO_REQUEST -> new AuctionHelloRequest(byteBuf);
            case CMSG_AUCTION_LIST_BIDDED_ITEMS -> new AuctionListBiddedItems(byteBuf);
            case CMSG_AUCTION_LIST_BIDDER_ITEMS -> new AuctionListBidderItems(byteBuf);
            case CMSG_AUCTION_LIST_BUCKETS_BY_BUCKET_KEYS -> new AuctionListBucketsByBucketKeys(byteBuf);
            case CMSG_AUCTION_LIST_ITEMS -> new AuctionListItems(byteBuf);
            case CMSG_AUCTION_LIST_ITEMS_BY_BUCKET_KEY -> new AuctionListItemsByBucketKey(byteBuf);
            case CMSG_AUCTION_LIST_ITEMS_BY_ITEM_ID -> new AuctionListItemsByItemID(byteBuf);
            case CMSG_AUCTION_LIST_OWNED_ITEMS -> new AuctionListOwnedItems(byteBuf);
            case CMSG_AUCTION_LIST_OWNER_ITEMS -> new AuctionListOwnerItems(byteBuf);
            case CMSG_AUCTION_LIST_PENDING_SALES -> new AuctionListPendingSales(byteBuf);
            case CMSG_AUCTION_PLACE_BID -> new AuctionPlaceBid(byteBuf);
            case CMSG_AUCTION_REMOVE_ITEM -> new AuctionRemoveItem(byteBuf);
            case CMSG_AUCTION_REPLICATE_ITEMS -> new AuctionReplicateItems(byteBuf);
            case CMSG_AUCTION_SELL_COMMODITY -> new AuctionSellCommodity(byteBuf);
            case CMSG_AUCTION_SELL_ITEM -> new AuctionSellItem(byteBuf);
            case CMSG_AUCTION_SET_FAVORITE_ITEM -> new AuctionSetFavoriteItem(byteBuf);
            case CMSG_AUCTIONABLE_TOKEN_SELL -> new AuctionableTokenSell(byteBuf);
            case CMSG_AUCTIONABLE_TOKEN_SELL_AT_MARKET_PRICE -> new AuctionableTokenSellAtMarketPrice(byteBuf);
            case CMSG_AUTH_CONTINUED_SESSION -> new AuthContinuedSession(byteBuf);
            case CMSG_AUTH_SESSION -> new AuthSession(byteBuf);
            case CMSG_AUTO_EQUIP_ITEM -> new AutoEquipItem(byteBuf);
            case CMSG_AUTO_EQUIP_ITEM_SLOT -> new AutoEquipItemSlot(byteBuf);
            case CMSG_AUTO_GUILD_BANK_ITEM -> new AutoGuildBankItem(byteBuf);
            case CMSG_AUTO_STORE_BAG_ITEM -> new AutoStoreBagItem(byteBuf);
            case CMSG_AUTO_STORE_GUILD_BANK_ITEM -> new AutoStoreGuildBankItem(byteBuf);
            case CMSG_AUTOBANK_ITEM -> new AutobankItem(byteBuf);
            case CMSG_AUTOSTORE_BANK_ITEM -> new AutoStoreBankItem(byteBuf);
            case CMSG_AZERITE_EMPOWERED_ITEM_SELECT_POWER -> new AzeriteEmpoweredItemSelectPower(byteBuf);
            case CMSG_AZERITE_EMPOWERED_ITEM_VIEWED -> new AzeriteEmpoweredItemViewed(byteBuf);
            case CMSG_AZERITE_ESSENCE_ACTIVATE_ESSENCE -> new AzeriteEssenceActivateEssence(byteBuf);
            case CMSG_AZERITE_ESSENCE_UNLOCK_MILESTONE -> new AzeriteEssenceUnlockMilestone(byteBuf);
            case CMSG_BANKER_ACTIVATE -> new BankerActivate(byteBuf);
            case CMSG_BATTLE_PAY_ACK_FAILED_RESPONSE -> new BattlePayAckFailedResponse(byteBuf);
            case CMSG_BATTLE_PAY_CANCEL_OPEN_CHECKOUT -> new BattlePayCancelOpenCheckout(byteBuf);
            case CMSG_BATTLE_PAY_CONFIRM_PURCHASE_RESPONSE -> new BattlePayConfirmPurchaseResponse(byteBuf);
            case CMSG_BATTLE_PAY_DISTRIBUTION_ASSIGN_TO_TARGET -> new BattlePayDistributionAssignToTarget(byteBuf);
            case CMSG_BATTLE_PAY_DISTRIBUTION_ASSIGN_VAS -> new BattlePayDistributionAssignVas(byteBuf);
            case CMSG_BATTLE_PAY_GET_PRODUCT_LIST -> new BattlePayGetProductList(byteBuf);
            case CMSG_BATTLE_PAY_GET_PURCHASE_LIST -> new BattlePayGetPurchaseList(byteBuf);
            case CMSG_BATTLE_PAY_OPEN_CHECKOUT -> new BattlePayOpenCheckout(byteBuf);
            case CMSG_BATTLE_PAY_REQUEST_PRICE_INFO -> new BattlePayRequestPriceInfo(byteBuf);
            case CMSG_BATTLE_PAY_START_PURCHASE -> new BattlePayStartPurchase(byteBuf);
            case CMSG_BATTLE_PAY_START_VAS_PURCHASE -> new BattlePayStartVasPurchase(byteBuf);
            case CMSG_BATTLE_PET_CLEAR_FANFARE -> new BattlePetClearFanfare(byteBuf);
            case CMSG_BATTLE_PET_DELETE_PET -> new BattlePetDeletePet(byteBuf);
            case CMSG_BATTLE_PET_DELETE_PET_CHEAT -> new BattlePetDeletePetCheat(byteBuf);
            case CMSG_BATTLE_PET_MODIFY_NAME -> new BattlePetModifyName(byteBuf);
            case CMSG_BATTLE_PET_REQUEST_JOURNAL -> new BattlePetRequestJournal(byteBuf);
            case CMSG_BATTLE_PET_REQUEST_JOURNAL_LOCK -> new BattlePetRequestJournalLock(byteBuf);
            case CMSG_BATTLE_PET_SET_BATTLE_SLOT -> new BattlePetSetBattleSlot(byteBuf);
            case CMSG_BATTLE_PET_SET_FLAGS -> new BattlePetSetFlags(byteBuf);
            case CMSG_BATTLE_PET_SUMMON -> new BattlePetSummon(byteBuf);
            case CMSG_BATTLE_PET_UPDATE_DISPLAY_NOTIFY -> new BattlePetUpdateDisplayNotify(byteBuf);
            case CMSG_BATTLE_PET_UPDATE_NOTIFY -> new BattlePetUpdateNotify(byteBuf);
            case CMSG_BATTLEFIELD_LEAVE -> new BattlefieldLeave(byteBuf);
            case CMSG_BATTLEFIELD_LIST -> new BattlefieldList(byteBuf);
            case CMSG_BATTLEFIELD_PORT -> new BattlefieldPort(byteBuf);
            case CMSG_BATTLEMASTER_HELLO -> new BattlemasterHello(byteBuf);
            case CMSG_BATTLEMASTER_JOIN -> new BattlemasterJoin(byteBuf);
            case CMSG_BATTLEMASTER_JOIN_ARENA -> new BattlemasterJoinArena(byteBuf);
            case CMSG_BATTLEMASTER_JOIN_SKIRMISH -> new BattlemasterJoinSkirmish(byteBuf);
            case CMSG_BATTLENET_CHALLENGE_RESPONSE -> new BattlenetChallengeResponse(byteBuf);
            case CMSG_BATTLENET_REQUEST -> new BattlenetRequest(byteBuf);
            case CMSG_BEGIN_TRADE -> new BeginTrade(byteBuf);
            case CMSG_BINDER_ACTIVATE -> new BinderActivate(byteBuf);
            case CMSG_BLACK_MARKET_BID_ON_ITEM -> new BlackMarketBidOnItem(byteBuf);
            case CMSG_BLACK_MARKET_OPEN -> new BlackMarketOpen(byteBuf);
            case CMSG_BLACK_MARKET_REQUEST_ITEMS -> new BlackMarketRequestItems(byteBuf);
            case CMSG_BUG_REPORT -> new BugReport(byteBuf);
            case CMSG_BUSY_TRADE -> new BusyTrade(byteBuf);
            case CMSG_BUY_BACK_ITEM -> new BuyBackItem(byteBuf);
            case CMSG_BUY_BANK_SLOT -> new BuyBankSlot(byteBuf);
            case CMSG_BUY_ITEM -> new BuyItem(byteBuf);
            case CMSG_BUY_STABLE_SLOT -> new BuyStableSlot(byteBuf); // NYI
            case CMSG_CAGE_BATTLE_PET -> new CageBattlePet(byteBuf);
            case CMSG_CALENDAR_ADD_EVENT -> new CalendarAddEvent(byteBuf);
            case CMSG_CALENDAR_COMMUNITY_INVITE -> new CalendarCommunityInvite(byteBuf);
            case CMSG_CALENDAR_COMPLAIN -> new CalendarComplain(byteBuf);
            case CMSG_CALENDAR_COPY_EVENT -> new CalendarCopyEvent(byteBuf);
            case CMSG_CALENDAR_EVENT_SIGN_UP -> new CalendarEventSignUp(byteBuf);
            case CMSG_CALENDAR_GET -> new CalendarGet(byteBuf);
            case CMSG_CALENDAR_GET_EVENT -> new CalendarGetEvent(byteBuf);
            case CMSG_CALENDAR_GET_NUM_PENDING -> new CalendarGetNumPending(byteBuf);
            case CMSG_CALENDAR_INVITE -> new CalendarInvite(byteBuf);
            case CMSG_CALENDAR_MODERATOR_STATUS -> new CalendarModeratorStatus(byteBuf);
            case CMSG_CALENDAR_REMOVE_EVENT -> new CalendarRemoveEvent(byteBuf);
            case CMSG_CALENDAR_REMOVE_INVITE -> new CalendarRemoveInvite(byteBuf);
            case CMSG_CALENDAR_RSVP -> new CalendarRsvp(byteBuf);
            case CMSG_CALENDAR_STATUS -> new CalendarStatus(byteBuf);
            case CMSG_CALENDAR_UPDATE_EVENT -> new CalendarUpdateEvent(byteBuf);
            case CMSG_CAN_DUEL -> new CanDuel(byteBuf);
            case CMSG_CAN_REDEEM_TOKEN_FOR_BALANCE -> new CanRedeemTokenForBalance(byteBuf);
            case CMSG_CANCEL_AURA -> new CancelAura(byteBuf);
            case CMSG_CANCEL_AUTO_REPEAT_SPELL -> new CancelAutoRepeatSpell(byteBuf);
            case CMSG_CANCEL_CAST -> new CancelCast(byteBuf);
            case CMSG_CANCEL_CHANNELLING -> new CancelChannelling(byteBuf);
            case CMSG_CANCEL_GROWTH_AURA -> new CancelGrowthAura(byteBuf);
            case CMSG_CANCEL_MOUNT_AURA -> new CancelMountAura(byteBuf);
            case CMSG_CANCEL_QUEUED_SPELL -> new CancelQueuedSpell(byteBuf);
            case CMSG_CANCEL_TEMP_ENCHANTMENT -> new CancelTempEnchantment(byteBuf);
            case CMSG_CANCEL_TRADE -> new CancelTrade(byteBuf);
            case CMSG_CAST_SPELL -> new CastSpell(byteBuf);
            case CMSG_CHALLENGE_MODE_REQUEST_LEADERS -> new ChallengeModeRequestLeaders(byteBuf); // NYI
            case CMSG_CHANGE_REALM_TICKET -> new ChangeRealmTicket(byteBuf);
            case CMSG_CHANGE_SUB_GROUP -> new ChangeSubGroup(byteBuf);
            case CMSG_CHAR_CREATE_FINALIZE_REINCARNATION -> new CharCreateFinalizeReincarnation(byteBuf);
            case CMSG_CHAR_CUSTOMIZE -> new CharCustomize(byteBuf);
            case CMSG_CHAR_DELETE -> new CharDelete(byteBuf);
            case CMSG_CHAR_RACE_OR_FACTION_CHANGE -> new CharRaceOrFactionChange(byteBuf);
            case CMSG_CHARACTER_CHECK_UPGRADE -> new CharacterCheckUpgrade(byteBuf);
            case CMSG_CHARACTER_RENAME_REQUEST -> new CharacterRenameRequest(byteBuf);
            case CMSG_CHARACTER_UPGRADE_MANUAL_UNREVOKE_REQUEST -> new CharacterUpgradeManualUnrevokeRequest(byteBuf);
            case CMSG_CHARACTER_UPGRADE_START -> new CharacterUpgradeStart(byteBuf);
            case CMSG_CHAT_ADDON_MESSAGE -> new ChatAddonMessage(byteBuf);
            case CMSG_CHAT_ADDON_MESSAGE_TARGETED -> new ChatAddonMessageTargeted(byteBuf);
            case CMSG_CHAT_CHANNEL_ANNOUNCEMENTS -> new ChatChannelAnnouncements(byteBuf);
            case CMSG_CHAT_CHANNEL_BAN -> new ChatChannelBan(byteBuf);
            case CMSG_CHAT_CHANNEL_DECLINE_INVITE -> new ChatChannelDeclineInvite(byteBuf);
            case CMSG_CHAT_CHANNEL_DISPLAY_LIST -> new ChatChannelDisplayList(byteBuf);
            case CMSG_CHAT_CHANNEL_INVITE -> new ChatChannelInvite(byteBuf);
            case CMSG_CHAT_CHANNEL_KICK -> new ChatChannelKick(byteBuf);
            case CMSG_CHAT_CHANNEL_LIST -> new ChatChannelList(byteBuf);
            case CMSG_CHAT_CHANNEL_MODERATE -> new ChatChannelModerate(byteBuf); // NYI
            case CMSG_CHAT_CHANNEL_MODERATOR -> new ChatChannelModerator(byteBuf);
            case CMSG_CHAT_CHANNEL_OWNER -> new ChatChannelOwner(byteBuf);
            case CMSG_CHAT_CHANNEL_PASSWORD -> new ChatChannelPassword(byteBuf);
            case CMSG_CHAT_CHANNEL_SET_OWNER -> new ChatChannelSetOwner(byteBuf);
            case CMSG_CHAT_CHANNEL_SILENCE_ALL -> new ChatChannelSilenceAll(byteBuf);
            case CMSG_CHAT_CHANNEL_UNBAN -> new ChatChannelUnban(byteBuf);
            case CMSG_CHAT_CHANNEL_UNMODERATOR -> new ChatChannelUnmoderator(byteBuf);
            case CMSG_CHAT_CHANNEL_UNSILENCE_ALL -> new ChatChannelUnsilenceAll(byteBuf);
            case CMSG_CHAT_DROP_CAUTIONARY_CHAT_MESSAGE -> new ChatDropCautionaryChatMessage(byteBuf); // NYI
            case CMSG_CHAT_JOIN_CHANNEL -> new ChatJoinChannel(byteBuf);
            case CMSG_CHAT_LEAVE_CHANNEL -> new ChatLeaveChannel(byteBuf);
            case CMSG_CHAT_MESSAGE_AFK -> new ChatMessageAfk(byteBuf);
            case CMSG_CHAT_MESSAGE_CHANNEL -> new ChatMessageChannel(byteBuf);
            case CMSG_CHAT_MESSAGE_DND -> new ChatMessageDnd(byteBuf);
            case CMSG_CHAT_MESSAGE_EMOTE -> new ChatMessageEmote(byteBuf);
            case CMSG_CHAT_MESSAGE_GUILD -> new ChatMessageGuild(byteBuf);
            case CMSG_CHAT_MESSAGE_INSTANCE_CHAT -> new ChatMessageInstanceChat(byteBuf);
            case CMSG_CHAT_MESSAGE_OFFICER -> new ChatMessageOfficer(byteBuf);
            case CMSG_CHAT_MESSAGE_PARTY -> new ChatMessageParty(byteBuf);
            case CMSG_CHAT_MESSAGE_RAID -> new ChatMessageRaid(byteBuf);
            case CMSG_CHAT_MESSAGE_RAID_WARNING -> new ChatMessageRaidWarning(byteBuf);
            case CMSG_CHAT_MESSAGE_SAY -> new ChatMessageSay(byteBuf);
            case CMSG_CHAT_MESSAGE_WHISPER -> new ChatMessageWhisper(byteBuf);
            case CMSG_CHAT_MESSAGE_YELL -> new ChatMessageYell(byteBuf);
            case CMSG_CHAT_REGISTER_ADDON_PREFIXES -> new ChatRegisterAddonPrefixes(byteBuf);
            case CMSG_CHAT_REPORT_FILTERED -> new ChatReportFiltered(byteBuf); // NYI
            case CMSG_CHAT_REPORT_IGNORED -> new ChatReportIgnored(byteBuf);
            case CMSG_CHAT_SEND_CAUTIONARY_CHANNEL_MESSAGE -> new ChatSendCautionaryChannelMessage(byteBuf); // NYI
            case CMSG_CHAT_SEND_CAUTIONARY_CHAT_MESSAGE -> new ChatSendCautionaryChatMessage(byteBuf); // NYI
            case CMSG_CHAT_UNREGISTER_ALL_ADDON_PREFIXES -> new ChatUnregisterAllAddonPrefixes(byteBuf);
            case CMSG_CHECK_IS_ADVENTURE_MAP_POI_VALID -> new CheckIsAdventureMapPoiValid(byteBuf);
            case CMSG_CHOICE_RESPONSE -> new ChoiceResponse(byteBuf);
            case CMSG_CLEAR_NEW_APPEARANCE -> new ClearNewAppearance(byteBuf); // NYI
            case CMSG_CLEAR_RAID_MARKER -> new ClearRaidMarker(byteBuf);
            case CMSG_CLEAR_TRADE_ITEM -> new ClearTradeItem(byteBuf);
            case CMSG_CLIENT_PORT_GRAVEYARD -> new ClientPortGraveyard(byteBuf);
            case CMSG_CLOSE_INTERACTION -> new CloseInteraction(byteBuf);
            case CMSG_CLOSE_QUEST_CHOICE -> new CloseQuestChoice(byteBuf);
            case CMSG_CLOSE_TRAIT_SYSTEM_INTERACTION -> new CloseTraitSystemInteraction(byteBuf);
            case CMSG_CLUB_FINDER_APPLICATION_RESPONSE -> new ClubFinderApplicationResponse(byteBuf);
            case CMSG_CLUB_FINDER_GET_APPLICANTS_LIST -> new ClubFinderGetApplicantsList(byteBuf);
            case CMSG_CLUB_FINDER_POST -> new ClubFinderPost(byteBuf);
            case CMSG_CLUB_FINDER_REQUEST_CLUBS_DATA -> new ClubFinderRequestClubsData(byteBuf);
            case CMSG_CLUB_FINDER_REQUEST_CLUBS_LIST -> new ClubFinderRequestClubsList(byteBuf);
            case CMSG_CLUB_FINDER_REQUEST_MEMBERSHIP_TO_CLUB -> new ClubFinderRequestMembershipToClub(byteBuf);
            case CMSG_CLUB_FINDER_REQUEST_PENDING_CLUBS_LIST -> new ClubFinderRequestPendingClubsList(byteBuf);
            case CMSG_CLUB_FINDER_REQUEST_SUBSCRIBED_CLUB_POSTING_IDS ->
                    new ClubFinderRequestSubscribedClubPostingIds(byteBuf);
            case CMSG_CLUB_FINDER_RESPOND_TO_APPLICANT -> new ClubFinderRespondToApplicant(byteBuf);
            case CMSG_CLUB_FINDER_WHISPER_APPLICANT_REQUEST -> new ClubFinderWhisperApplicantRequest(byteBuf);
            case CMSG_CLUB_PRESENCE_SUBSCRIBE -> new ClubPresenceSubscribe(byteBuf);
            case CMSG_COLLECTION_ITEM_SET_FAVORITE -> new CollectionItemSetFavorite(byteBuf);
            case CMSG_COMMENTATOR_ENABLE -> new CommentatorEnable(byteBuf);
            case CMSG_COMMENTATOR_ENTER_INSTANCE -> new CommentatorEnterInstance(byteBuf);
            case CMSG_COMMENTATOR_EXIT_INSTANCE -> new CommentatorExitInstance(byteBuf);
            case CMSG_COMMENTATOR_GET_MAP_INFO -> new CommentatorGetMapInfo(byteBuf);
            case CMSG_COMMENTATOR_GET_PLAYER_COOLDOWNS -> new CommentatorGetPlayerCooldowns(byteBuf);
            case CMSG_COMMENTATOR_GET_PLAYER_INFO -> new CommentatorGetPlayerInfo(byteBuf);
            case CMSG_COMMENTATOR_START_WARGAME -> new CommentatorStartWargame(byteBuf);
            case CMSG_COMMERCE_TOKEN_GET_COUNT -> new CommerceTokenGetCount(byteBuf);
            case CMSG_COMMERCE_TOKEN_GET_LOG -> new CommerceTokenGetLog(byteBuf);
            case CMSG_COMMERCE_TOKEN_GET_MARKET_PRICE -> new CommerceTokenGetMarketPrice(byteBuf);
            case CMSG_COMPLAINT -> new Complaint(byteBuf);
            case CMSG_COMPLETE_CINEMATIC -> new CompleteCinematic(byteBuf);
            case CMSG_COMPLETE_MOVIE -> new CompleteMovie(byteBuf);
            case CMSG_CONFIRM_BARBERS_CHOICE -> new ConfirmBarbersChoice(byteBuf);
            case CMSG_CONFIRM_RESPEC_WIPE -> new ConfirmRespecWipe(byteBuf);
            case CMSG_CONNECT_TO_FAILED -> new ConnectToFailed(byteBuf);
            case CMSG_CONSUMABLE_TOKEN_BUY -> new ConsumableTokenBuy(byteBuf);
            case CMSG_CONSUMABLE_TOKEN_BUY_AT_MARKET_PRICE -> new ConsumableTokenBuyAtMarketPrice(byteBuf);
            case CMSG_CONSUMABLE_TOKEN_CAN_VETERAN_BUY -> new ConsumableTokenCanVeteranBuy(byteBuf);
            case CMSG_CONSUMABLE_TOKEN_REDEEM -> new ConsumableTokenRedeem(byteBuf);
            case CMSG_CONSUMABLE_TOKEN_REDEEM_CONFIRMATION -> new ConsumableTokenRedeemConfirmation(byteBuf);
            case CMSG_CONTRIBUTION_LAST_UPDATE_REQUEST -> new ContributionLastUpdateRequest(byteBuf);
            case CMSG_CONVERSATION_LINE_STARTED -> new ConversationLineStarted(byteBuf);
            case CMSG_CONVERT_RAID -> new ConvertRaid(byteBuf);
            case CMSG_CREATE_CHARACTER -> new CreateCharacter(byteBuf);
            case CMSG_DB_QUERY_BULK -> new DbQueryBulk(byteBuf);
            case CMSG_DECLINE_GUILD_INVITES -> new DeclineGuildInvites(byteBuf);
            case CMSG_DECLINE_PETITION -> new DeclinePetition(byteBuf);
            case CMSG_DEL_FRIEND -> new DelFriend(byteBuf);
            case CMSG_DEL_IGNORE -> new DelIgnore(byteBuf);
            case CMSG_DELETE_EQUIPMENT_SET -> new DeleteEquipmentSet(byteBuf);
            case CMSG_DESTROY_ITEM -> new DestroyItem(byteBuf);
            case CMSG_DF_BOOT_PLAYER_VOTE -> new DfBootPlayerVote(byteBuf);
            case CMSG_DF_GET_JOIN_STATUS -> new DfGetJoinStatus(byteBuf);
            case CMSG_DF_GET_SYSTEM_INFO -> new DfGetSystemInfo(byteBuf);
            case CMSG_DF_JOIN -> new DfJoin(byteBuf);
            case CMSG_DF_LEAVE -> new DfLeave(byteBuf);
            case CMSG_DF_PROPOSAL_RESPONSE -> new DfProposalResponse(byteBuf);
            case CMSG_DF_READY_CHECK_RESPONSE -> new DfReadyCheckResponse(byteBuf);
            case CMSG_DF_SET_ROLES -> new DfSetRoles(byteBuf);
            case CMSG_DF_TELEPORT -> new DfTeleport(byteBuf);
            case CMSG_DISCARDED_TIME_SYNC_ACKS -> new DiscardedTimeSyncAcks(byteBuf);
            case CMSG_DISMISS_CRITTER -> new DismissCritter(byteBuf);
            case CMSG_DO_COUNTDOWN -> new DoCountdown(byteBuf);
            case CMSG_DO_READY_CHECK -> new DoReadyCheck(byteBuf);
            case CMSG_DUEL_RESPONSE -> new DuelResponse(byteBuf);
            case CMSG_EJECT_PASSENGER -> new EjectPassenger(byteBuf);
            case CMSG_EMOTE -> new Emote(byteBuf);
            case CMSG_ENABLE_NAGLE -> new EnableNagle(byteBuf);
            case CMSG_ENABLE_TAXI_NODE -> new EnableTaxiNode(byteBuf);
            case CMSG_ENGINE_SURVEY -> new EngineSurvey(byteBuf);
            case CMSG_ENTER_ENCRYPTED_MODE_ACK -> new EnterEncryptedModeAck(byteBuf);
            case CMSG_ENUM_CHARACTERS -> new EnumCharacters(byteBuf);
            case CMSG_ENUM_CHARACTERS_DELETED_BY_CLIENT -> new EnumCharactersDeletedByClient(byteBuf);
            case CMSG_FAR_SIGHT -> new FarSight(byteBuf);
            case CMSG_GAME_EVENT_DEBUG_DISABLE -> new GameEventDebugDisable(byteBuf);
            case CMSG_GAME_EVENT_DEBUG_ENABLE -> new GameEventDebugEnable(byteBuf);
            case CMSG_GAME_OBJ_REPORT_USE -> new GameObjReportUse(byteBuf);
            case CMSG_GAME_OBJ_USE -> new GameObjUse(byteBuf);
            case CMSG_GENERATE_RANDOM_CHARACTER_NAME -> new GenerateRandomCharacterName(byteBuf);
            case CMSG_GET_ACCOUNT_CHARACTER_LIST -> new GetAccountCharacterList(byteBuf);
            case CMSG_GET_ACCOUNT_NOTIFICATIONS -> new GetAccountNotifications(byteBuf);
            case CMSG_GET_ITEM_PURCHASE_DATA -> new GetItemPurchaseData(byteBuf);
            case CMSG_GET_MIRROR_IMAGE_DATA -> new GetMirrorImageData(byteBuf);
            case CMSG_GET_PVP_OPTIONS_ENABLED -> new GetPvpOptionsEnabled(byteBuf);
            case CMSG_GET_REMAINING_GAME_TIME -> new GetRemainingGameTime(byteBuf);
            case CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS -> new GetUndeleteCharacterCooldownStatus(byteBuf);
            case CMSG_GET_VAS_ACCOUNT_CHARACTER_LIST -> new GetVasAccountCharacterList(byteBuf);
            case CMSG_GET_VAS_TRANSFER_TARGET_REALM_LIST -> new GetVasTransferTargetRealmList(byteBuf);
            case CMSG_GM_TICKET_ACKNOWLEDGE_SURVEY -> new GmTicketAcknowledgeSurvey(byteBuf);
            case CMSG_GM_TICKET_GET_CASE_STATUS -> new GmTicketGetCaseStatus(byteBuf);
            case CMSG_GM_TICKET_GET_SYSTEM_STATUS -> new GmTicketGetSystemStatus(byteBuf);
            case CMSG_GOSSIP_SELECT_OPTION -> new GossipSelectOption(byteBuf);
            case CMSG_GUILD_ADD_BATTLENET_FRIEND -> new GuildAddBattlenetFriend(byteBuf); // NYI
            case CMSG_GUILD_ADD_RANK -> new GuildAddRank(byteBuf);
            case CMSG_GUILD_ASSIGN_MEMBER_RANK -> new GuildAssignMemberRank(byteBuf);
            case CMSG_GUILD_BANK_ACTIVATE -> new GuildBankActivate(byteBuf);
            case CMSG_GUILD_BANK_BUY_TAB -> new GuildBankBuyTab(byteBuf);
            case CMSG_GUILD_BANK_DEPOSIT_MONEY -> new GuildBankDepositMoney(byteBuf);
            case CMSG_GUILD_BANK_LOG_QUERY -> new GuildBankLogQuery(byteBuf);
            case CMSG_GUILD_BANK_QUERY_TAB -> new GuildBankQueryTab(byteBuf);
            case CMSG_GUILD_BANK_REMAINING_WITHDRAW_MONEY_QUERY -> new GuildBankRemainingWithdrawMoneyQuery(byteBuf);
            case CMSG_GUILD_BANK_SET_TAB_TEXT -> new GuildBankSetTabText(byteBuf);
            case CMSG_GUILD_BANK_TEXT_QUERY -> new GuildBankTextQuery(byteBuf);
            case CMSG_GUILD_BANK_UPDATE_TAB -> new GuildBankUpdateTab(byteBuf);
            case CMSG_GUILD_BANK_WITHDRAW_MONEY -> new GuildBankWithdrawMoney(byteBuf);
            case CMSG_GUILD_CHALLENGE_UPDATE_REQUEST -> new GuildChallengeUpdateRequest(byteBuf);
            case CMSG_GUILD_CHANGE_NAME_REQUEST -> new GuildChangeNameRequest(byteBuf);
            case CMSG_GUILD_DECLINE_INVITATION -> new GuildDeclineInvitation(byteBuf);
            case CMSG_GUILD_DELETE -> new GuildDelete(byteBuf);
            case CMSG_GUILD_DELETE_RANK -> new GuildDeleteRank(byteBuf);
            case CMSG_GUILD_DEMOTE_MEMBER -> new GuildDemoteMember(byteBuf);
            case CMSG_GUILD_EVENT_LOG_QUERY -> new GuildEventLogQuery(byteBuf);
            case CMSG_GUILD_GET_ACHIEVEMENT_MEMBERS -> new GuildGetAchievementMembers(byteBuf);
            case CMSG_GUILD_GET_RANKS -> new GuildGetRanks(byteBuf);
            case CMSG_GUILD_GET_ROSTER -> new GuildGetRoster(byteBuf);
            case CMSG_GUILD_INVITE_BY_NAME -> new GuildInviteByName(byteBuf);
            case CMSG_GUILD_LEAVE -> new GuildLeave(byteBuf);
            case CMSG_GUILD_NEWS_UPDATE_STICKY -> new GuildNewsUpdateSticky(byteBuf);
            case CMSG_GUILD_OFFICER_REMOVE_MEMBER -> new GuildOfficerRemoveMember(byteBuf);
            case CMSG_GUILD_PERMISSIONS_QUERY -> new GuildPermissionsQuery(byteBuf);
            case CMSG_GUILD_PROMOTE_MEMBER -> new GuildPromoteMember(byteBuf);
            case CMSG_GUILD_QUERY_MEMBER_RECIPES -> new GuildQueryMemberRecipes(byteBuf);
            case CMSG_GUILD_QUERY_NEWS -> new GuildQueryNews(byteBuf);
            case CMSG_GUILD_QUERY_RECIPES -> new GuildQueryRecipes(byteBuf);
            case CMSG_GUILD_REPLACE_GUILD_MASTER -> new GuildReplaceGuildMaster(byteBuf);
            case CMSG_GUILD_REQUEST_RENAME -> new GuildRequestRename(byteBuf); // NYI
            case CMSG_GUILD_REQUEST_RENAME_NAME_CHECK -> new GuildRequestRenameNameCheck(byteBuf); // NYI
            case CMSG_GUILD_REQUEST_RENAME_REFUND -> new GuildRequestRenameRefund(byteBuf); // NYI
            case CMSG_GUILD_REQUEST_RENAME_STATUS -> new GuildRequestRenameStatus(byteBuf);
            case CMSG_GUILD_SET_ACHIEVEMENT_TRACKING -> new GuildSetAchievementTracking(byteBuf);
            case CMSG_GUILD_SET_FOCUSED_ACHIEVEMENT -> new GuildSetFocusedAchievement(byteBuf);
            case CMSG_GUILD_SET_GUILD_MASTER -> new GuildSetGuildMaster(byteBuf);
            case CMSG_GUILD_SET_MEMBER_NOTE -> new GuildSetMemberNote(byteBuf);
            case CMSG_GUILD_SET_RANK_PERMISSIONS -> new GuildSetRankPermissions(byteBuf);
            case CMSG_GUILD_SHIFT_RANK -> new GuildShiftRank(byteBuf);
            case CMSG_GUILD_UPDATE_INFO_TEXT -> new GuildUpdateInfoText(byteBuf);
            case CMSG_GUILD_UPDATE_MOTD_TEXT -> new GuildUpdateMotdText(byteBuf);
            case CMSG_HEARTH_AND_RESURRECT -> new HearthAndResurrect(byteBuf);
            case CMSG_HOTFIX_REQUEST -> new HotfixRequest(byteBuf);
            case CMSG_IGNORE_TRADE -> new IgnoreTrade(byteBuf);
            case CMSG_INITIATE_ROLE_POLL -> new InitiateRolePoll(byteBuf);
            case CMSG_INITIATE_TRADE -> new InitiateTrade(byteBuf);
            case CMSG_INSPECT -> new Inspect(byteBuf);
            case CMSG_INITIATE_ROLE_POLL -> null;
            case CMSG_INITIATE_TRADE -> new InitiateTrade(byteBuf);
            case CMSG_INSPECT -> new Inspect(byteBuf);
            case CMSG_INSPECT_PVP -> null;
            case CMSG_INSTANCE_LOCK_RESPONSE -> new InstanceLockResponse(byteBuf);
            case CMSG_ITEM_PURCHASE_REFUND -> new ItemPurchaseRefund(byteBuf);
            case CMSG_ITEM_TEXT_QUERY -> new ItemTextQuery(byteBuf);
            case CMSG_JOIN_PET_BATTLE_QUEUE -> new JoinPetBattleQueue(byteBuf);
            case CMSG_JOIN_RATED_BATTLEGROUND -> new JoinRatedBattleground(byteBuf);
            case CMSG_KEEP_ALIVE -> new KeepAlive(byteBuf);
            case CMSG_KEYBOUND_OVERRIDE -> new KeyboundOverride(byteBuf);
            case _LATENCY_REPORT -> new LatencyReport(byteBuf);
            case CMSG_LEARN_PET_SPECIALIZATION_GROUP -> new LearnPetSpecializationGroup(byteBuf);
            case CMSG_LEARN_PREVIEW_TALENTS -> new LearnPreviewTalents(byteBuf);
            case CMSG_LEARN_PREVIEW_TALENTS_PET -> new LearnPreviewTalentsPet(byteBuf);
            case CMSG_LEARN_TALENT -> new LearnTalent(byteBuf);
            case CMSG_LEARN_TALENTS -> new LearnTalents(byteBuf);
            case CMSG_LEAVE_GROUP -> new LeaveGroup(byteBuf);
            case CMSG_LEAVE_PET_BATTLE_QUEUE -> new LeavePetBattleQueue(byteBuf);
            case CMSG_LFG_LIST_APPLY_TO_GROUP -> new LfgListApplyToGroup(byteBuf);
            case CMSG_LFG_LIST_CANCEL_APPLICATION -> new LfgListCancelApplication(byteBuf);
            case CMSG_LFG_LIST_DECLINE_APPLICANT -> null;
            case CMSG_LFG_LIST_GET_STATUS -> new LfgListGetStatus(byteBuf);
            case CMSG_LFG_LIST_INVITE_APPLICANT -> new LfgListInviteApplicant(byteBuf);
            case CMSG_LFG_LIST_INVITE_RESPONSE -> new LfgListInviteResponse(byteBuf);
            case CMSG_LFG_LIST_JOIN -> new LfgListJoin(byteBuf);
            case CMSG_LFG_LIST_LEAVE -> new LfgListLeave(byteBuf);
            case CMSG_LFG_LIST_SEARCH -> new LfgListSearch(byteBuf);
            case CMSG_LFG_LIST_SET_ROLES -> new LfgListSetRoles(byteBuf);
            case CMSG_LFG_LIST_UPDATE_REQUEST -> new LfgListUpdateRequest(byteBuf);
            case CMSG_LIST_INVENTORY -> new ListInventory(byteBuf);
            case CMSG_LIVE_REGION_ACCOUNT_RESTORE -> new LiveRegionAccountRestore(byteBuf);
            case CMSG_LIVE_REGION_CHARACTER_COPY -> new LiveRegionCharacterCopy(byteBuf);
            case CMSG_LIVE_REGION_GET_ACCOUNT_CHARACTER_LIST -> new LiveRegionGetAccountCharacterList(byteBuf);
            case CMSG_LOADING_SCREEN_NOTIFY -> null;
            case CMSG_LOBBY_MATCHMAKER_ENTER_QUEUE -> new LobbyMatchmakerEnterQueue(byteBuf);
            case CMSG_LOG_DISCONNECT -> null;
            case CMSG_LOG_STREAMING_ERROR -> null;
            case CMSG_LOGOUT_CANCEL -> null;
            case CMSG_LOGOUT_INSTANT -> null;
            case CMSG_LOGOUT_REQUEST -> null;
            case CMSG_LOOT_ITEM -> new LootItem(byteBuf);
            case CMSG_LOOT_MONEY -> new LootMoney(byteBuf);
            case CMSG_LOOT_RELEASE -> new LootRelease(byteBuf);
            case CMSG_LOOT_ROLL -> new LootRoll(byteBuf);
            case CMSG_LOOT_UNIT -> new LootUnit(byteBuf);
            case CMSG_LOW_LEVEL_RAID1 -> null;
            case CMSG_LOW_LEVEL_RAID2 -> null;
            case CMSG_MAIL_CREATE_TEXT_ITEM -> new MailCreateTextItem(byteBuf);
            case CMSG_MAIL_DELETE -> new MailDelete(byteBuf);
            case CMSG_MAIL_GET_LIST -> new MailGetList(byteBuf);
            case CMSG_MAIL_MARK_AS_READ -> new MailMarkAsRead(byteBuf);
            case CMSG_MAIL_RETURN_TO_SENDER -> new MailReturnToSender(byteBuf);
            case CMSG_MAIL_TAKE_ITEM -> new MailTakeItem(byteBuf);
            case CMSG_MAIL_TAKE_MONEY -> new MailTakeMoney(byteBuf);
            case CMSG_MAKE_CONTITIONAL_APPEARANCE_PERMANENT -> null;
            case CMSG_MASTER_LOOT_ITEM -> new MasterLootItem(byteBuf);
            case CMSG_MERGE_GUILD_BANK_ITEM_WITH_GUILD_BANK_ITEM -> new MergeGuildBankItemWithGuildBankItem(byteBuf);
            case CMSG_MERGE_GUILD_BANK_ITEM_WITH_ITEM -> new MergeGuildBankItemWithItem(byteBuf);
            case CMSG_MERGE_ITEM_WITH_GUILD_BANK_ITEM -> new MergeItemWithGuildBankItem(byteBuf);
            case CMSG_MINIMAP_PING -> null;
            case CMSG_MISSILE_TRAJECTORY_COLLISION -> null;
            case CMSG_MOUNT_CLEAR_FANFARE -> null; // NYI
            case CMSG_MOUNT_SET_FAVORITE -> null;
            case CMSG_MOUNT_SPECIAL_ANIM -> null;
            case CMSG_MOVE_ADD_IMPULSE_ACK -> new MoveAddImpulseAck(byteBuf);
            case CMSG_MOVE_APPLY_INERTIA_ACK -> new MoveApplyInertiaAck(byteBuf);
            case CMSG_MOVE_APPLY_MOVEMENT_FORCE_ACK -> new MoveApplyMovementForceAck(byteBuf);
            case CMSG_MOVE_CHANGE_TRANSPORT -> new MoveChangeTransport(byteBuf);
            case CMSG_MOVE_CHANGE_VEHICLE_SEATS -> new MoveChangeVehicleSeats(byteBuf);
            case CMSG_MOVE_COLLISION_DISABLE_ACK -> new MoveCollisionDisableAck(byteBuf);
            case CMSG_MOVE_COLLISION_ENABLE_ACK -> new MoveCollisionEnableAck(byteBuf);
            case CMSG_MOVE_DISMISS_VEHICLE -> null;
            case CMSG_MOVE_DOUBLE_JUMP -> null;
            case CMSG_MOVE_ENABLE_DOUBLE_JUMP_ACK -> new MoveEnableDoubleJumpAck(byteBuf);
            case CMSG_MOVE_ENABLE_FULL_SPEED_TURNING_ACK -> new MoveEnableFullSpeedTurningAck(byteBuf);
            case CMSG_MOVE_ENABLE_SWIM_TO_FLY_TRANS_ACK -> new MoveEnableSwimToFlyTransAck(byteBuf);
            case CMSG_MOVE_FALL_LAND -> new MoveFallLand(byteBuf);
            case CMSG_MOVE_FALL_RESET -> new MoveFallReset(byteBuf);
            case CMSG_MOVE_FEATHER_FALL_ACK -> new MoveFeatherFallAck(byteBuf);
            case CMSG_MOVE_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK -> new MoveForceFlightBackSpeedChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_FLIGHT_SPEED_CHANGE_ACK -> new MoveForceFlightSpeedChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_PITCH_RATE_CHANGE_ACK -> new MoveForcePitchRateChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_ROOT_ACK -> new MoveForceRootAck(byteBuf);
            case CMSG_MOVE_FORCE_RUN_BACK_SPEED_CHANGE_ACK -> new MoveForceRunBackSpeedChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK -> new MoveForceRunSpeedChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_SWIM_BACK_SPEED_CHANGE_ACK -> new MoveForceSwimBackSpeedChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_SWIM_SPEED_CHANGE_ACK -> new MoveForceSwimSpeedChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_TURN_RATE_CHANGE_ACK -> new MoveForceTurnRateChangeAck(byteBuf);
            case CMSG_MOVE_FORCE_UNROOT_ACK -> new MoveForceUnrootAck(byteBuf);
            case CMSG_MOVE_FORCE_WALK_SPEED_CHANGE_ACK -> new MoveForceWalkSpeedChangeAck(byteBuf);
            case CMSG_MOVE_GRAVITY_DISABLE_ACK -> null;
            case CMSG_MOVE_GRAVITY_ENABLE_ACK -> new MoveGravityEnableAck(byteBuf);
            case CMSG_MOVE_GUILD_BANK_ITEM -> new MoveGuildBankItem(byteBuf);
            case CMSG_MOVE_HEARTBEAT -> new MoveHeartbeat(byteBuf);
            case CMSG_MOVE_HOVER_ACK -> new MoveHoverAck(byteBuf);
            case CMSG_MOVE_INERTIA_DISABLE_ACK -> new MoveInertiaDisableAck(byteBuf);
            case CMSG_MOVE_INERTIA_ENABLE_ACK -> new MoveInertiaEnableAck(byteBuf);
            case CMSG_MOVE_INIT_ACTIVE_MOVER_COMPLETE -> new MoveInitActiveMoverComplete(byteBuf);
            case CMSG_MOVE_JUMP -> new MoveJump(byteBuf);
            case CMSG_MOVE_KNOCK_BACK_ACK -> new MoveKnockBackAck(byteBuf);
            case CMSG_MOVE_REMOVE_INERTIA_ACK -> new MoveRemoveInertiaAck(byteBuf);
            case CMSG_MOVE_REMOVE_MOVEMENT_FORCE_ACK -> new MoveRemoveMovementForceAck(byteBuf);
            case CMSG_MOVE_REMOVE_MOVEMENT_FORCES -> new MoveRemoveMovementForces(byteBuf);
            case CMSG_MOVE_SET_ADV_FLY -> new MoveSetAdvFly(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_ADD_IMPULSE_MAX_SPEED_ACK -> new MoveSetAdvFlyingAddImpulseMaxSpeedAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_AIR_FRICTION_ACK -> new MoveSetAdvFlyingAirFrictionAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_BANKING_RATE_ACK -> new MoveSetAdvFlyingBankingRateAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_DOUBLE_JUMP_VEL_MOD_ACK -> new MoveSetAdvFlyingDoubleJumpVelModAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_GLIDE_START_MIN_HEIGHT_ACK ->
                    new MoveSetAdvFlyingGlideStartMinHeightAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_LAUNCH_SPEED_COEFFICIENT_ACK ->
                    new MoveSetAdvFlyingLaunchSpeedCoefficientAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_LIFT_COEFFICIENT_ACK -> new MoveSetAdvFlyingLiftCoefficientAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_MAX_VEL_ACK -> new MoveSetAdvFlyingMaxVelAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_OVER_MAX_DECELERATION_ACK ->
                    new MoveSetAdvFlyingOverMaxDecelerationAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_PITCHING_RATE_DOWN_ACK -> new MoveSetAdvFlyingPitchRateDownAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_PITCHING_RATE_UP_ACK -> new MoveSetAdvFlyingPitchRateUpAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_SURFACE_FRICTION_ACK -> new MoveSetAdvFlyingSurfaceFrictionAck(byteBuf);
            case CMSG_MOVE_SET_ADV_FLYING_TURN_VELOCITY_THRESHOLD_ACK ->
                    new MoveSetAdvFlyingTurnVelocityThresholdAck(byteBuf);
            case CMSG_MOVE_SET_CAN_ADV_FLY_ACK -> new MoveSetCanAdvFlyAck(byteBuf);
            case CMSG_MOVE_SET_CAN_DRIVE_ACK -> new MoveSetCanDriveAck(byteBuf);
            case CMSG_MOVE_SET_CAN_FLY_ACK -> new MoveSetCanFlyAck(byteBuf);
            case CMSG_MOVE_SET_CAN_TURN_WHILE_FALLING_ACK -> new MoveSetCanTurnWhileFallingAck(byteBuf);
            case CMSG_MOVE_SET_COLLISION_HEIGHT_ACK -> new MoveSetCollisionHeightAck(byteBuf);
            case CMSG_MOVE_SET_FACING -> new MoveSetFacing(byteBuf);
            case CMSG_MOVE_SET_FACING_HEARTBEAT -> new MoveSetFacingHeartbeat(byteBuf);
            case CMSG_MOVE_SET_FLY -> new MoveSetFly(byteBuf);
            case CMSG_MOVE_SET_IGNORE_MOVEMENT_FORCES_ACK -> new MoveSetIgnoreMovementForcesAck(byteBuf);
            case CMSG_MOVE_SET_MOD_MOVEMENT_FORCE_MAGNITUDE_ACK -> new MoveSetModMovementForceMagnitudeAck(byteBuf);
            case CMSG_MOVE_SET_PITCH -> new MoveSetPitch(byteBuf);
            case CMSG_MOVE_SET_RUN_MODE -> new MoveSetRunMode(byteBuf);
            case CMSG_MOVE_SET_TURN_RATE_CHEAT -> new MoveSetTurnRateCheat(byteBuf);
            case CMSG_MOVE_SET_VEHICLE_REC_ID_ACK -> new MoveSetVehicleRecIDAck(byteBuf);
            case CMSG_MOVE_SET_WALK_MODE -> new MoveSetWalkMode(byteBuf);
            case CMSG_MOVE_SPLINE_DONE -> new MoveSplineDone(byteBuf);
            case CMSG_MOVE_START_ASCEND -> new MoveStartAscend(byteBuf);
            case CMSG_MOVE_START_BACKWARD -> new MoveStartBackward(byteBuf);
            case CMSG_MOVE_START_DESCEND -> new MoveStartDescend(byteBuf);
            case CMSG_MOVE_START_DRIVE_FORWARD -> new MoveStartDriveForward(byteBuf);
            case CMSG_MOVE_START_FORWARD -> new MoveStartForward(byteBuf);
            case CMSG_MOVE_START_PITCH_DOWN -> new MoveStartPitchDown(byteBuf);
            case CMSG_MOVE_START_PITCH_UP -> new MoveStartPitchUp(byteBuf);
            case CMSG_MOVE_START_STRAFE_LEFT -> new MoveStartStrafeLeft(byteBuf);
            case CMSG_MOVE_START_STRAFE_RIGHT -> new MoveStartStrafeRight(byteBuf);
            case CMSG_MOVE_START_SWIM -> new MoveStartSwim(byteBuf);
            case CMSG_MOVE_START_TURN_LEFT -> new MoveStartTurnLeft(byteBuf);
            case CMSG_MOVE_START_TURN_RIGHT -> new MoveStartTurnRight(byteBuf);
            case CMSG_MOVE_STOP -> new MoveStop(byteBuf);
            case CMSG_MOVE_STOP_ASCEND -> new MoveStopAscend(byteBuf);
            case CMSG_MOVE_STOP_PITCH -> new MoveStopPitch(byteBuf);
            case CMSG_MOVE_STOP_STRAFE -> new MoveStopStrafe(byteBuf);
            case CMSG_MOVE_STOP_SWIM -> new MoveStopSwim(byteBuf);
            case CMSG_MOVE_STOP_TURN -> new MoveStopTurn(byteBuf);
            case CMSG_MOVE_TELEPORT_ACK -> new MoveTeleportAck(byteBuf);
            case CMSG_MOVE_TIME_SKIPPED -> new MoveTimeSkipped(byteBuf);
            case CMSG_MOVE_UPDATE_FALL_SPEED -> new MoveUpdateFallSpeed(byteBuf);
            case CMSG_MOVE_WATER_WALK_ACK -> new MoveWaterWalkAck(byteBuf);
            case CMSG_MYTHIC_PLUS_REQUEST_MAP_STATS -> new MythicPlusRequestMapStats(byteBuf);
            case CMSG_NEUTRAL_PLAYER_SELECT_FACTION -> new NeutralPlayerSelectFaction(byteBuf);
            case CMSG_NEXT_CINEMATIC_CAMERA -> new NextCinematicCamera(byteBuf);
            case CMSG_OBJECT_UPDATE_FAILED -> new ObjectUpdateFailed(byteBuf);
            case CMSG_OBJECT_UPDATE_RESCUED -> new ObjectUpdateRescued(byteBuf);
            case CMSG_OFFER_PETITION -> new OfferPetition(byteBuf);
            case CMSG_OPEN_ITEM -> new OpenItem(byteBuf);
            case CMSG_OPENING_CINEMATIC -> new OpeningCinematic(byteBuf);
            case CMSG_OPT_OUT_OF_LOOT -> new OptOutOfLoot(byteBuf);
            case CMSG_OVERRIDE_SCREEN_FLASH -> new OverrideScreenFlash(byteBuf);
            case CMSG_PARTY_INVITE -> new PartyInvite(byteBuf);
            case CMSG_PARTY_INVITE_RESPONSE -> new PartyInviteResponse(byteBuf);
            case CMSG_PARTY_UNINVITE -> new PartyUninvite(byteBuf);
            case CMSG_PET_ABANDON -> new PetAbandon(byteBuf);
            case CMSG_PET_ACTION -> new PetAction(byteBuf);
            case CMSG_PET_BATTLE_FINAL_NOTIFY -> new PetBattleFinalNotify(byteBuf);
            case CMSG_PET_BATTLE_INPUT -> new PetBattleInput(byteBuf);
            case CMSG_PET_BATTLE_QUEUE_PROPOSE_MATCH_RESULT -> new PetBattleQueueProposeMatchResult(byteBuf);
            case CMSG_PET_BATTLE_QUIT_NOTIFY -> new PetBattleQuitNotify(byteBuf);
            case CMSG_PET_BATTLE_REPLACE_FRONT_PET -> new PetBattleReplaceFrontPet(byteBuf);
            case CMSG_PET_BATTLE_REQUEST_PVP -> new PetBattleRequestPVP(byteBuf);
            case CMSG_PET_BATTLE_REQUEST_UPDATE -> new PetBattleRequestUpdate(byteBuf);
            case CMSG_PET_BATTLE_REQUEST_WILD -> new PetBattleRequestWild(byteBuf);
            case CMSG_PET_BATTLE_SCRIPT_ERROR_NOTIFY -> new PetBattleScriptErrorNotify(byteBuf);
            case CMSG_PET_CANCEL_AURA -> new PetCancelAura(byteBuf);
            case CMSG_PET_CAST_SPELL -> new PetCastSpell(byteBuf);
            case CMSG_PET_LEARN_TALENT -> new PetLearnTalent(byteBuf);
            case CMSG_PET_RENAME -> new PetRename(byteBuf);
            case CMSG_PET_SET_ACTION -> new PetSetAction(byteBuf);
            case CMSG_PET_SPELL_AUTOCAST -> new PetSpellAutocast(byteBuf);
            case CMSG_PET_STOP_ATTACK -> new PetStopAttack(byteBuf);
            case CMSG_PETITION_BUY -> new PetitionBuy(byteBuf);
            case CMSG_PETITION_RENAME_GUILD -> new PetitionRenameGuild(byteBuf);
            case CMSG_PETITION_SHOW_LIST -> new PetitionShowList(byteBuf);
            case CMSG_PETITION_SHOW_SIGNATURES -> new PetitionShowSignatures(byteBuf);
            case CMSG_PING -> new Ping(byteBuf);
            case CMSG_PLAYER_LOGIN -> new PlayerLogin(byteBuf);
            case CMSG_PUSH_QUEST_TO_PARTY -> new PushQuestToParty(byteBuf);
            case CMSG_PVP_LOG_DATA -> new PvpLogData(byteBuf);
            case CMSG_QUERY_ARENA_TEAM -> new QueryArenaTeam(byteBuf);
            case CMSG_QUERY_BATTLE_PET_NAME -> new QueryBattlePetName(byteBuf);
            case CMSG_QUERY_CORPSE_LOCATION_FROM_CLIENT -> new QueryCorpseLocationFromClient(byteBuf);
            case CMSG_QUERY_CORPSE_TRANSPORT -> new QueryCorpseTransport(byteBuf);
            case CMSG_QUERY_COUNTDOWN_TIMER -> new QueryCountdownTimer(byteBuf);
            case CMSG_QUERY_CREATURE -> new QueryCreature(byteBuf);
            case CMSG_QUERY_GAME_OBJECT -> new QueryGameObject(byteBuf);
            case CMSG_QUERY_GUILD_INFO -> new QueryGuildInfo(byteBuf);
            case CMSG_QUERY_INSPECT_ACHIEVEMENTS -> new QueryInspectAchievements(byteBuf);
            case CMSG_QUERY_NEXT_MAIL_TIME -> new QueryNextMailTime(byteBuf);
            case CMSG_QUERY_NPC_TEXT -> new QueryNpcText(byteBuf);
            case CMSG_QUERY_PAGE_TEXT -> new QueryPageText(byteBuf);
            case CMSG_QUERY_PET_NAME -> new QueryPetName(byteBuf);
            case CMSG_QUERY_PETITION -> new QueryPetition(byteBuf);
            case CMSG_QUERY_PLAYER_NAME_BY_COMMUNITY_ID -> new QueryPlayerNameByCommunityId(byteBuf);
            case CMSG_QUERY_PLAYER_NAMES -> new QueryPlayerNames(byteBuf);
            case CMSG_QUERY_PLAYER_NAMES_FOR_COMMUNITY -> new QueryPlayerNamesForCommunity(byteBuf);
            case CMSG_QUERY_QUEST_COMPLETION_NPCS -> new QueryQuestCompletionNpcs(byteBuf);
            case CMSG_QUERY_QUEST_INFO -> new QueryQuestInfo(byteBuf);
            case CMSG_QUERY_QUEST_ITEM_USABILITY -> new QueryQuestItemUsability(byteBuf);
            case CMSG_QUERY_REALM_NAME -> new QueryRealmName(byteBuf);
            case CMSG_QUERY_SCENARIO_POI -> new QueryScenarioPoi(byteBuf);
            case CMSG_QUERY_TIME -> new QueryTime(byteBuf);
            case CMSG_QUERY_TREASURE_PICKER -> new QueryTreasurePicker(byteBuf);
            case CMSG_QUERY_VOID_STORAGE -> new QueryVoidStorage(byteBuf);
            case CMSG_QUEST_CONFIRM_ACCEPT -> new QuestConfirmAccept(byteBuf);
            case CMSG_QUEST_GIVER_ACCEPT_QUEST -> new QuestGiverAcceptQuest(byteBuf);
            case CMSG_QUEST_GIVER_CHOOSE_REWARD -> new QuestGiverChooseReward(byteBuf);
            case CMSG_QUEST_GIVER_CLOSE_QUEST -> new QuestGiverCloseQuest(byteBuf);
            case CMSG_QUEST_GIVER_COMPLETE_QUEST -> new QuestGiverCompleteQuest(byteBuf);
            case CMSG_QUEST_GIVER_HELLO -> new QuestGiverHello(byteBuf);
            case CMSG_QUEST_GIVER_QUERY_QUEST -> new QuestGiverQueryQuest(byteBuf);
            case CMSG_QUEST_GIVER_REQUEST_REWARD -> new QuestGiverRequestReward(byteBuf);
            case CMSG_QUEST_GIVER_STATUS_MULTIPLE_QUERY -> new QuestGiverStatusMultipleQuery(byteBuf);
            case CMSG_QUEST_GIVER_STATUS_QUERY -> new QuestGiverStatusQuery(byteBuf);
            case CMSG_QUEST_GIVER_STATUS_TRACKED_QUERY -> new QuestGiverStatusTrackedQuery(byteBuf);
            case CMSG_QUEST_LOG_REMOVE_QUEST -> new QuestLogRemoveQuest(byteBuf);
            case CMSG_QUEST_POI_QUERY -> new QuestPoiQuery(byteBuf);
            case CMSG_QUEST_PUSH_RESULT -> new QuestPushResult(byteBuf);
            case CMSG_QUEUED_MESSAGES_END -> new QueuedMessagesEnd(byteBuf);
            case CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS -> new QuickJoinAutoAcceptRequests(byteBuf);
            case CMSG_QUICK_JOIN_REQUEST_INVITE -> new QuickJoinRequestInvite(byteBuf);
            case CMSG_QUICK_JOIN_RESPOND_TO_INVITE -> new QuickJoinRespondToInvite(byteBuf);
            case CMSG_RAF_CLAIM_ACTIVITY_REWARD -> new RafClaimActivityReward(byteBuf);
            case CMSG_RAF_CLAIM_NEXT_REWARD -> new RafClaimNextReward(byteBuf);
            case CMSG_RAF_GENERATE_RECRUITMENT_LINK -> new RafGenerateRecruitmentLink(byteBuf);
            case CMSG_RAF_UPDATE_RECRUITMENT_INFO -> new RafUpdateRecruitmentInfo(byteBuf);
            case CMSG_RANDOM_ROLL -> new RandomRoll(byteBuf);
            case CMSG_READ_ITEM -> new ReadItem(byteBuf);
            case CMSG_READY_CHECK_RESPONSE -> new ReadyCheckResponse(byteBuf);
            case CMSG_RECLAIM_CORPSE -> new ReclaimCorpse(byteBuf);
            case CMSG_REFORGE_ITEM -> new ReforgeItem(byteBuf);
            case CMSG_REMOVE_GLYPH -> new RemoveGlyph(byteBuf);
            case CMSG_REMOVE_NEW_ITEM -> new RemoveNewItem(byteBuf);
            case CMSG_REMOVE_RAF_RECRUIT -> new RemoveRafRecruit(byteBuf);
            case CMSG_REORDER_CHARACTERS -> new ReorderCharacters(byteBuf);
            case CMSG_REPAIR_ITEM -> new RepairItem(byteBuf);
            case CMSG_REPOP_REQUEST -> new RepopRequest(byteBuf);
            case CMSG_REPORT_PVP_PLAYER_AFK -> new ReportPvpPlayerAfk(byteBuf);
            case CMSG_REPORT_SERVER_LAG -> new ReportServerLag(byteBuf);
            case CMSG_REQUEST_ACCOUNT_DATA -> new RequestAccountData(byteBuf);
            case CMSG_REQUEST_AREA_POI_UPDATE -> new RequestAreaPoiUpdate(byteBuf);
            case CMSG_REQUEST_BATTLEFIELD_STATUS -> new RequestBattlefieldStatus(byteBuf);
            case CMSG_REQUEST_CEMETERY_LIST -> new RequestCemeteryList(byteBuf);
            case CMSG_REQUEST_CROWD_CONTROL_SPELL -> new RequestCrowdControlSpell(byteBuf);
            case CMSG_REQUEST_GUILD_PARTY_STATE -> new RequestGuildPartyState(byteBuf);
            case CMSG_REQUEST_GUILD_REWARDS_LIST -> new RequestGuildRewardsList(byteBuf);
            case CMSG_REQUEST_HONOR_STATS -> new RequestHonorStats(byteBuf);
            case CMSG_REQUEST_LFG_LIST_BLACKLIST -> new RequestLfgListBlacklist(byteBuf);
            case CMSG_REQUEST_MYTHIC_PLUS_AFFIXES -> new RequestMythicPlusAffixes(byteBuf);
            case CMSG_REQUEST_MYTHIC_PLUS_SEASON_DATA -> new RequestMythicPlusSeasonData(byteBuf);
            case CMSG_REQUEST_PARTY_JOIN_UPDATES -> new RequestPartyJoinUpdates(byteBuf);
            case CMSG_REQUEST_PARTY_MEMBER_STATS -> new RequestPartyMemberStats(byteBuf);
            case CMSG_REQUEST_PET_INFO -> new RequestPetInfo(byteBuf);
            case CMSG_REQUEST_PLAYED_TIME -> new RequestPlayedTime(byteBuf);
            case CMSG_REQUEST_PVP_REWARDS -> new RequestPvpRewards(byteBuf);
            case CMSG_REQUEST_RAID_INFO -> new RequestRaidInfo(byteBuf);
            case CMSG_REQUEST_RATED_PVP_INFO -> new RequestRatedPvpInfo(byteBuf);
            case CMSG_REQUEST_SCHEDULED_PVP_INFO -> new RequestScheduledPvpInfo(byteBuf);
            case CMSG_REQUEST_STABLED_PETS -> new RequestStabledPets(byteBuf);
            case CMSG_REQUEST_STORE_FRONT_INFO_UPDATE -> new RequestStoreFrontInfoUpdate(byteBuf);
            case CMSG_REQUEST_VEHICLE_EXIT -> new RequestVehicleExit(byteBuf);
            case CMSG_REQUEST_VEHICLE_NEXT_SEAT -> new RequestVehicleNextSeat(byteBuf);
            case CMSG_REQUEST_VEHICLE_PREV_SEAT -> new RequestVehiclePrevSeat(byteBuf);
            case CMSG_REQUEST_VEHICLE_SWITCH_SEAT -> new RequestVehicleSwitchSeat(byteBuf);
            case CMSG_REQUEST_WORLD_QUEST_UPDATE -> new RequestWorldQuestUpdate(byteBuf);
            case CMSG_RESET_CHALLENGE_MODE -> new ResetChallengeMode(byteBuf);
            case CMSG_RESET_INSTANCES -> new ResetInstances(byteBuf);
            case CMSG_RESURRECT_RESPONSE -> new ResurrectResponse(byteBuf);
            case CMSG_RIDE_VEHICLE_INTERACT -> new RideVehicleInteract(byteBuf);
            case CMSG_SAVE_ACCOUNT_DATA_EXPORT -> new SaveAccountDataExport(byteBuf);
            case CMSG_SAVE_CUF_PROFILES -> new SaveCufProfiles(byteBuf);
            case CMSG_SAVE_EQUIPMENT_SET -> new SaveEquipmentSet(byteBuf);
            case CMSG_SAVE_GUILD_EMBLEM -> new SaveGuildEmblem(byteBuf);
            case CMSG_SCENE_PLAYBACK_CANCELED -> new ScenePlaybackCanceled(byteBuf);
            case CMSG_SCENE_PLAYBACK_COMPLETE -> new ScenePlaybackComplete(byteBuf);
            case CMSG_SCENE_TRIGGER_EVENT -> new SceneTriggerEvent(byteBuf);
            case CMSG_SEAMLESS_TRANSFER_COMPLETE -> new SeamlessTransferComplete(byteBuf);
            case CMSG_SELF_RES -> new SelfRes(byteBuf);
            case CMSG_SELL_ITEM -> new SellItem(byteBuf);
            case CMSG_SEND_CONTACT_LIST -> new SendContactList(byteBuf);
            case CMSG_SEND_MAIL -> new SendMail(byteBuf);
            case CMSG_SEND_TEXT_EMOTE -> new SendTextEmote(byteBuf);
            case CMSG_SERVER_TIME_OFFSET_REQUEST -> new ServerTimeOffsetRequest(byteBuf);
            case CMSG_SET_ACTION_BAR_TOGGLES -> new SetActionBarToggles(byteBuf);
            case CMSG_SET_ACTION_BUTTON -> new SetActionButton(byteBuf);
            case CMSG_SET_ACTIVE_MOVER -> new SetActiveMover(byteBuf);
            case CMSG_SET_ADVANCED_COMBAT_LOGGING -> new SetAdvancedCombatLogging(byteBuf);
            case CMSG_SET_AMMO -> new SetAmmo(byteBuf);
            case CMSG_SET_ASSISTANT_LEADER -> new SetAssistantLeader(byteBuf);
            case CMSG_SET_CONTACT_NOTES -> new SetContactNotes(byteBuf);
            case CMSG_SET_CURRENCY_FLAGS -> new SetCurrencyFlags(byteBuf);
            case CMSG_SET_DIFFICULTY_ID -> new SetDifficultyId(byteBuf);
            case CMSG_SET_DUNGEON_DIFFICULTY -> new SetDungeonDifficulty(byteBuf);
            case CMSG_SET_EVERYONE_IS_ASSISTANT -> new SetEveryoneIsAssistant(byteBuf);
            case CMSG_SET_FACTION_AT_WAR -> new SetFactionAtWar(byteBuf);
            case CMSG_SET_FACTION_INACTIVE -> new SetFactionInactive(byteBuf);
            case CMSG_SET_FACTION_NOT_AT_WAR -> new SetFactionNotAtWar(byteBuf);
            case CMSG_SET_GAME_EVENT_DEBUG_VIEW_STATE -> new SetGameEventDebugViewState(byteBuf);
            case CMSG_SET_INSERT_ITEMS_LEFT_TO_RIGHT -> new SetInsertItemsLeftToRight(byteBuf);
            case CMSG_SET_LOOT_METHOD -> new SetLootMethod(byteBuf);
            case CMSG_SET_LOOT_SPECIALIZATION -> new SetLootSpecialization(byteBuf);
            case CMSG_SET_PARTY_ASSIGNMENT -> new SetPartyAssignment(byteBuf);
            case CMSG_SET_PARTY_LEADER -> new SetPartyLeader(byteBuf);
            case CMSG_SET_PET_SLOT -> new SetPetSlot(byteBuf);
            case CMSG_SET_PET_SPECIALIZATION -> new SetPetSpecialization(byteBuf);
            case CMSG_SET_PLAYER_DECLINED_NAMES -> new SetPlayerDeclinedNames(byteBuf);
            case CMSG_SET_PREFERRED_CEMETERY -> new SetPreferredCemetery(byteBuf);
            case CMSG_SET_PRIMARY_TALENT_TREE -> new SetPrimaryTalentTree(byteBuf);
            case CMSG_SET_PVP -> new SetPvp(byteBuf);
            case CMSG_SET_RAID_DIFFICULTY -> new SetRaidDifficulty(byteBuf);
            case CMSG_SET_ROLE -> new SetRole(byteBuf);
            case CMSG_SET_SAVED_INSTANCE_EXTEND -> new SetSavedInstanceExtend(byteBuf);
            case CMSG_SET_SELECTION -> new SetSelection(byteBuf);
            case CMSG_SET_SHEATHED -> new SetSheathed(byteBuf);
            case CMSG_SET_TAXI_BENCHMARK_MODE -> new SetTaxiBenchmarkMode(byteBuf);
            case CMSG_SET_TITLE -> new SetTitle(byteBuf);
            case CMSG_SET_TRADE_GOLD -> new SetTradeGold(byteBuf);
            case CMSG_SET_TRADE_ITEM -> new SetTradeItem(byteBuf);
            case CMSG_SET_WATCHED_FACTION -> new SetWatchedFaction(byteBuf);
            case CMSG_SHOW_TRADE_SKILL -> new ShowTradeSkill(byteBuf);
            case CMSG_SHOWING_CLOAK -> new ShowingCloak(byteBuf);
            case CMSG_SHOWING_HELM -> new ShowingHelm(byteBuf);
            case CMSG_SIGN_PETITION -> new SignPetition(byteBuf);
            case CMSG_SILENCE_PARTY_TALKER -> new SilencePartyTalker(byteBuf);
            case CMSG_SOCIAL_CONTRACT_REQUEST -> new SocialContractRequest(byteBuf);
            case CMSG_SOCKET_GEMS -> new SocketGems(byteBuf);
            case CMSG_SPAWN_TRACKING_UPDATE -> new SpawnTrackingUpdate(byteBuf);
            case CMSG_SPELL_CLICK -> new SpellClick(byteBuf);
            case CMSG_SPIRIT_HEALER_ACTIVATE -> new SpiritHealerActivate(byteBuf);
            case CMSG_SPLIT_GUILD_BANK_ITEM -> new SplitGuildBankItem(byteBuf);
            case CMSG_SPLIT_GUILD_BANK_ITEM_TO_INVENTORY -> new SplitGuildBankItemToInventory(byteBuf);
            case CMSG_SPLIT_ITEM -> new SplitItem(byteBuf);
            case CMSG_SPLIT_ITEM_TO_GUILD_BANK -> new SplitItemToGuildBank(byteBuf);
            case CMSG_STAND_STATE_CHANGE -> new StandStateChange(byteBuf);
            case CMSG_START_SPECTATOR_WAR_GAME -> new StartSpectatorWarGame(byteBuf);
            case CMSG_START_WAR_GAME -> new StartWarGame(byteBuf);
            case CMSG_STORE_GUILD_BANK_ITEM -> new StoreGuildBankItem(byteBuf);
            case CMSG_SUBMIT_USER_FEEDBACK -> new SubmitUserFeedback(byteBuf);
            case CMSG_SUMMON_RESPONSE -> new SummonResponse(byteBuf);
            case CMSG_SUPPORT_TICKET_SUBMIT_BUG -> new SupportTicketSubmitBug(byteBuf);
            case CMSG_SUPPORT_TICKET_SUBMIT_COMPLAINT -> new SupportTicketSubmitComplaint(byteBuf);
            case CMSG_SUPPORT_TICKET_SUBMIT_SUGGESTION -> new SupportTicketSubmitSuggestion(byteBuf);
            case CMSG_SUSPEND_COMMS_ACK -> new SuspendCommsAck(byteBuf);
            case CMSG_SUSPEND_TOKEN_RESPONSE -> new SuspendTokenResponse(byteBuf);
            case CMSG_SWAP_GUILD_BANK_ITEM_WITH_GUILD_BANK_ITEM -> new SwapGuildBankItemWithGuildBankItem(byteBuf);
            case CMSG_SWAP_INV_ITEM -> new SwapInvItem(byteBuf);
            case CMSG_SWAP_ITEM -> new SwapItem(byteBuf);
            case CMSG_SWAP_ITEM_WITH_GUILD_BANK_ITEM -> new SwapItemWithGuildBankItem(byteBuf);
            case CMSG_SWAP_SUB_GROUPS -> new SwapSubGroups(byteBuf);
            case CMSG_SWAP_VOID_ITEM -> new SwapVoidItem(byteBuf);
            case CMSG_TABARD_VENDOR_ACTIVATE -> new TabardVendorActivate(byteBuf);
            case CMSG_TALK_TO_GOSSIP -> new TalkToGossip(byteBuf);
            case CMSG_TAXI_NODE_STATUS_QUERY -> new TaxiNodeStatusQuery(byteBuf);
            case CMSG_TAXI_QUERY_AVAILABLE_NODES -> new TaxiQueryAvailableNodes(byteBuf);
            case CMSG_TAXI_REQUEST_EARLY_LANDING -> new TaxiRequestEarlyLanding(byteBuf);
            case CMSG_TIME_ADJUSTMENT_RESPONSE -> new TimeAdjustmentResponse(byteBuf);
            case CMSG_TIME_SYNC_RESPONSE -> new TimeSyncResponse(byteBuf);
            case CMSG_TIME_SYNC_RESPONSE_DROPPED -> new TimeSyncResponseDropped(byteBuf);
            case CMSG_TIME_SYNC_RESPONSE_FAILED -> new TimeSyncResponseFailed(byteBuf);
            case CMSG_TOGGLE_DIFFICULTY -> new ToggleDifficulty(byteBuf);
            case CMSG_TOGGLE_PVP -> new TogglePvp(byteBuf);
            case CMSG_TOTEM_DESTROYED -> new TotemDestroyed(byteBuf);
            case CMSG_TOY_CLEAR_FANFARE -> new ToyClearFanfare(byteBuf);
            case CMSG_TRAINER_BUY_SPELL -> new TrainerBuySpell(byteBuf);
            case CMSG_TRAINER_LIST -> new TrainerList(byteBuf);
            case CMSG_TRAITS_COMMIT_CONFIG -> new TraitsCommitConfig(byteBuf);
            case CMSG_TRANSMOGRIFY_ITEMS -> new TransmogrifyItems(byteBuf);
            case CMSG_TURN_IN_PETITION -> new TurnInPetition(byteBuf);
            case CMSG_TUTORIAL -> new Tutorial(byteBuf);
            case CMSG_UNACCEPT_TRADE -> new UnacceptTrade(byteBuf);
            case CMSG_UNDELETE_CHARACTER -> new UndeleteCharacter(byteBuf);
            case CMSG_UNLEARN_SKILL -> new UnlearnSkill(byteBuf);
            case CMSG_UNLEARN_SPECIALIZATION -> new UnlearnSpecialization(byteBuf);
            case CMSG_UNLOCK_VOID_STORAGE -> new UnlockVoidStorage(byteBuf);
            case CMSG_UPDATE_AADC_STATUS -> new UpdateAADCStatus(byteBuf);
            case CMSG_UPDATE_ACCOUNT_DATA -> new UpdateAccountData(byteBuf);
            case CMSG_UPDATE_AREA_TRIGGER_VISUAL -> new UpdateAreaTriggerVisual(byteBuf);
            case CMSG_UPDATE_CLIENT_SETTINGS -> new UpdateClientSettings(byteBuf);
            case CMSG_UPDATE_MISSILE_TRAJECTORY -> new UpdateMissileTrajectory(byteBuf);
            case CMSG_UPDATE_RAID_TARGET -> new UpdateRaidTarget(byteBuf);
            case CMSG_UPDATE_SPELL_VISUAL -> new UpdateSpellVisual(byteBuf);
            case CMSG_UPDATE_VAS_PURCHASE_STATES -> new UpdateVASPurchaseStates(byteBuf);
            case CMSG_UPGRADE_ITEM -> new UpgradeItem(byteBuf);
            case CMSG_USE_CRITTER_ITEM -> new UseCritterItem(byteBuf);
            case CMSG_USE_EQUIPMENT_SET -> new UseEquipmentSet(byteBuf);
            case CMSG_USE_ITEM -> new UseItem(byteBuf);
            case CMSG_USE_TOY -> new UseToy(byteBuf);
            case CMSG_USED_FOLLOW -> new UsedFollow(byteBuf);
            case CMSG_VAS_CHECK_TRANSFER_OK -> new VasCheckTransferOk(byteBuf);
            case CMSG_VAS_GET_QUEUE_MINUTES -> new VasGetQueueMinutes(byteBuf);
            case CMSG_VAS_GET_SERVICE_STATUS -> new VasGetServiceStatus(byteBuf);
            case CMSG_VIOLENCE_LEVEL -> new ViolenceLevel(byteBuf);
            case CMSG_VOICE_CHANNEL_STT_TOKEN_REQUEST -> new VoiceChannelSttTokenRequest(byteBuf);
            case CMSG_VOICE_CHAT_JOIN_CHANNEL -> new VoiceChatJoinChannel(byteBuf);
            case CMSG_VOICE_CHAT_LOGIN -> new VoiceChatLogin(byteBuf);
            case CMSG_VOID_STORAGE_TRANSFER -> new VoidStorageTransfer(byteBuf);
            case CMSG_WARDEN3_DATA -> new Warden3Data(byteBuf);
            case CMSG_WHO -> new Who(byteBuf);
            case CMSG_WHO_IS -> new WhoIs(byteBuf);
            case CMSG_WORLD_PORT_RESPONSE -> new WorldPortResponse(byteBuf);
            case CMSG_WRAP_ITEM -> new WrapItem(byteBuf);
        };
    }
}
